# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.serialization import FieldMetadata
from ...core.unchecked_base_model import UncheckedBaseModel


class ConjunctionDataEvent(UncheckedBaseModel):
    conjunction_data_event_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="conjunctionDataEventId"),
        pydantic.Field(alias="conjunctionDataEventId"),
    ] = None
    tca: typing.Optional[str] = None
    miss_distance: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="missDistance"), pydantic.Field(alias="missDistance")
    ] = None
    collision_probability: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="collisionProbability"),
        pydantic.Field(alias="collisionProbability"),
    ] = None
    object1object_designator: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="object1ObjectDesignator"),
        pydantic.Field(alias="object1ObjectDesignator"),
    ] = None
    object2object_designator: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="object2ObjectDesignator"),
        pydantic.Field(alias="object2ObjectDesignator"),
    ] = None
    creation_date: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="creationDate"), pydantic.Field(alias="creationDate")
    ] = None
    offset: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
