# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ..types.schema_response import SchemaResponse
from .raw_client import AsyncRawSchemasClient, RawSchemasClient


class SchemasClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSchemasClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSchemasClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSchemasClient
        """
        return self._raw_client

    def get_xsd(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[SchemaResponse]:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[SchemaResponse]
            OK

        Examples
        --------
        from tracss import TraCSS

        client = TraCSS(
            client_id="YOUR_CLIENT_ID", client_secret="YOUR_CLIENT_SECRET",
        )
        client.bulk_data.schemas.get_xsd()
        """
        _response = self._raw_client.get_xsd(request_options=request_options)
        return _response.data

    def download_xsd(
        self, filename: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Iterator[bytes]:
        """
        Parameters
        ----------
        filename : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.Iterator[bytes]
            OK

        Examples
        --------
        from tracss import TraCSS

        client = TraCSS(
            client_id="YOUR_CLIENT_ID", client_secret="YOUR_CLIENT_SECRET",
        )
        client.bulk_data.schemas.download_xsd(
            filename="filename",
        )
        """
        with self._raw_client.download_xsd(
            filename, request_options=request_options
        ) as r:
            yield from r.data

    def get_json(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[SchemaResponse]:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[SchemaResponse]
            OK

        Examples
        --------
        from tracss import TraCSS

        client = TraCSS(
            client_id="YOUR_CLIENT_ID", client_secret="YOUR_CLIENT_SECRET",
        )
        client.bulk_data.schemas.get_json()
        """
        _response = self._raw_client.get_json(request_options=request_options)
        return _response.data

    def download_json(
        self, filename: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Iterator[bytes]:
        """
        Parameters
        ----------
        filename : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.Iterator[bytes]
            OK

        Examples
        --------
        from tracss import TraCSS

        client = TraCSS(
            client_id="YOUR_CLIENT_ID", client_secret="YOUR_CLIENT_SECRET",
        )
        client.bulk_data.schemas.download_json(
            filename="filename",
        )
        """
        with self._raw_client.download_json(
            filename, request_options=request_options
        ) as r:
            yield from r.data


class AsyncSchemasClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSchemasClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSchemasClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSchemasClient
        """
        return self._raw_client

    async def get_xsd(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[SchemaResponse]:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[SchemaResponse]
            OK

        Examples
        --------
        import asyncio

        from tracss import AsyncTraCSS

        client = AsyncTraCSS(
            client_id="YOUR_CLIENT_ID", client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.bulk_data.schemas.get_xsd()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_xsd(request_options=request_options)
        return _response.data

    async def download_xsd(
        self, filename: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.AsyncIterator[bytes]:
        """
        Parameters
        ----------
        filename : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.AsyncIterator[bytes]
            OK

        Examples
        --------
        import asyncio

        from tracss import AsyncTraCSS

        client = AsyncTraCSS(
            client_id="YOUR_CLIENT_ID", client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.bulk_data.schemas.download_xsd(
                filename="filename",
            )


        asyncio.run(main())
        """
        async with self._raw_client.download_xsd(
            filename, request_options=request_options
        ) as r:
            async for _chunk in r.data:
                yield _chunk

    async def get_json(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[SchemaResponse]:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[SchemaResponse]
            OK

        Examples
        --------
        import asyncio

        from tracss import AsyncTraCSS

        client = AsyncTraCSS(
            client_id="YOUR_CLIENT_ID", client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.bulk_data.schemas.get_json()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_json(request_options=request_options)
        return _response.data

    async def download_json(
        self, filename: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.AsyncIterator[bytes]:
        """
        Parameters
        ----------
        filename : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.AsyncIterator[bytes]
            OK

        Examples
        --------
        import asyncio

        from tracss import AsyncTraCSS

        client = AsyncTraCSS(
            client_id="YOUR_CLIENT_ID", client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.bulk_data.schemas.download_json(
                filename="filename",
            )


        asyncio.run(main())
        """
        async with self._raw_client.download_json(
            filename, request_options=request_options
        ) as r:
            async for _chunk in r.data:
                yield _chunk
