repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
        args: [--fix]
        files: "^(sdks/python/tracss/client\\.py|tests/)"
      - id: ruff-format
        files: "^(sdks/python/tracss/client\\.py|tests/)"

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: system
        entry: uv run mypy
        files: "^(sdks/python/tracss/client\\.py|tests/)"
        types: [python]
        pass_filenames: false
        args: ["sdks/python/tracss/client.py", "tests/"]
