# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from .raw_client import AsyncRawTipClient, RawTipClient


class TipClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawTipClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawTipClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawTipClient
        """
        return self._raw_client

    def stream(
        self,
        *,
        norad_id: typing.Optional[str] = None,
        id: typing.Optional[str] = None,
        msg_epoch: typing.Optional[str] = None,
        insert_epoch: typing.Optional[str] = None,
        decay_epoch: typing.Optional[str] = None,
        window: typing.Optional[str] = None,
        rev: typing.Optional[str] = None,
        direction: typing.Optional[str] = None,
        latitude: typing.Optional[str] = None,
        longitude: typing.Optional[str] = None,
        inclination: typing.Optional[str] = None,
        next_report: typing.Optional[str] = None,
        high_interest: typing.Optional[str] = None,
        format: typing.Optional[str] = None,
        size: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Iterator[typing.Any]:
        """
        Find all TIP reports in the system or all reports that meet your search criteria defined by the query parameters.

        Parameters
        ----------
        norad_id : typing.Optional[str]
            The noradId of an object. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        id : typing.Optional[str]
            The numeric id of the TIP report. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        msg_epoch : typing.Optional[str]
            Timestamp of when of the TIP report was produced. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), Between (=Value1...Value2)

        insert_epoch : typing.Optional[str]
            Timestamp of when the record was inserted in the system. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), Between (=Value1...Value2)

        decay_epoch : typing.Optional[str]
            Timestamp of the predicted time of atmospheric re-entry. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), Between (=Value1...Value2)

        window : typing.Optional[str]
            The uncertainty window around the re-entry time in seconds. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        rev : typing.Optional[str]
            The orbit revolution number at the time of prediction. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        direction : typing.Optional[str]
            The direction of orbital trajectory during re-entry prediction. Valid operators are: Equal (=Value), Not Equal (=<>Value), Like (=\\*Value), Not Like (=~*Value). Possible values: ascending and descending.

        latitude : typing.Optional[str]
            The latitude of predicted re-entry location. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        longitude : typing.Optional[str]
            Longitude of predicted re-entry location. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        inclination : typing.Optional[str]
            Inclination of the orbit at time of prediction. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        next_report : typing.Optional[str]
            Estimated time in hours until next update (Integer). Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        high_interest : typing.Optional[str]
            Flag indicating if object is considered high interest for re-entry tracking. Valid operators are: Equal (=Value), Not Equal (=<>Value), Like (=\\*Value), Not Like (=~*Value). Possible values: Y, N

        format : typing.Optional[str]
            Format of the request body. KVN, JSON, and XML are all valid formats. JSON is default.

        size : typing.Optional[int]
            Number of TIP Reports to return.

        page : typing.Optional[int]
            Page number for the queried TIP(s), indexed by 0 (first page). Default is 0

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.Iterator[typing.Any]
            Ok - TIP(s) successfully retrieved.  Available formats are KVN (Text, Default), JSON, and XML.

        Examples
        --------
        from tracss import TraCSS

        client = TraCSS(
            client_id="YOUR_CLIENT_ID", client_secret="YOUR_CLIENT_SECRET",
        )
        response = client.bulk_data.tip.stream(
            norad_id="noradId=12345",
            id="id=87",
            msg_epoch="msgEpoch=2004-09-28T02:49:00.000Z",
            insert_epoch="insertEpoch=2004-09-28T02:49:00.000Z",
            decay_epoch="decayEpoch=2004-09-28T02:49:00.000Z",
            window="window=900",
            rev="rev=25952",
            direction="direction=descending",
            latitude="latitude=36.0",
            longitude="longitude=217.5",
            inclination="inclination=53.0",
            next_report="decayEpoch=48",
            high_interest="highInterest=Y",
            format="json",
        )
        for chunk in response:
            yield chunk
        """
        with self._raw_client.stream(
            norad_id=norad_id,
            id=id,
            msg_epoch=msg_epoch,
            insert_epoch=insert_epoch,
            decay_epoch=decay_epoch,
            window=window,
            rev=rev,
            direction=direction,
            latitude=latitude,
            longitude=longitude,
            inclination=inclination,
            next_report=next_report,
            high_interest=high_interest,
            format=format,
            size=size,
            page=page,
            request_options=request_options,
        ) as r:
            yield from r.data


class AsyncTipClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawTipClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawTipClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawTipClient
        """
        return self._raw_client

    async def stream(
        self,
        *,
        norad_id: typing.Optional[str] = None,
        id: typing.Optional[str] = None,
        msg_epoch: typing.Optional[str] = None,
        insert_epoch: typing.Optional[str] = None,
        decay_epoch: typing.Optional[str] = None,
        window: typing.Optional[str] = None,
        rev: typing.Optional[str] = None,
        direction: typing.Optional[str] = None,
        latitude: typing.Optional[str] = None,
        longitude: typing.Optional[str] = None,
        inclination: typing.Optional[str] = None,
        next_report: typing.Optional[str] = None,
        high_interest: typing.Optional[str] = None,
        format: typing.Optional[str] = None,
        size: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.AsyncIterator[typing.Any]:
        """
        Find all TIP reports in the system or all reports that meet your search criteria defined by the query parameters.

        Parameters
        ----------
        norad_id : typing.Optional[str]
            The noradId of an object. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        id : typing.Optional[str]
            The numeric id of the TIP report. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        msg_epoch : typing.Optional[str]
            Timestamp of when of the TIP report was produced. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), Between (=Value1...Value2)

        insert_epoch : typing.Optional[str]
            Timestamp of when the record was inserted in the system. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), Between (=Value1...Value2)

        decay_epoch : typing.Optional[str]
            Timestamp of the predicted time of atmospheric re-entry. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), Between (=Value1...Value2)

        window : typing.Optional[str]
            The uncertainty window around the re-entry time in seconds. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        rev : typing.Optional[str]
            The orbit revolution number at the time of prediction. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        direction : typing.Optional[str]
            The direction of orbital trajectory during re-entry prediction. Valid operators are: Equal (=Value), Not Equal (=<>Value), Like (=\\*Value), Not Like (=~*Value). Possible values: ascending and descending.

        latitude : typing.Optional[str]
            The latitude of predicted re-entry location. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        longitude : typing.Optional[str]
            Longitude of predicted re-entry location. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        inclination : typing.Optional[str]
            Inclination of the orbit at time of prediction. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        next_report : typing.Optional[str]
            Estimated time in hours until next update (Integer). Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        high_interest : typing.Optional[str]
            Flag indicating if object is considered high interest for re-entry tracking. Valid operators are: Equal (=Value), Not Equal (=<>Value), Like (=\\*Value), Not Like (=~*Value). Possible values: Y, N

        format : typing.Optional[str]
            Format of the request body. KVN, JSON, and XML are all valid formats. JSON is default.

        size : typing.Optional[int]
            Number of TIP Reports to return.

        page : typing.Optional[int]
            Page number for the queried TIP(s), indexed by 0 (first page). Default is 0

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.AsyncIterator[typing.Any]
            Ok - TIP(s) successfully retrieved.  Available formats are KVN (Text, Default), JSON, and XML.

        Examples
        --------
        import asyncio

        from tracss import AsyncTraCSS

        client = AsyncTraCSS(
            client_id="YOUR_CLIENT_ID", client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            response = await client.bulk_data.tip.stream(
                norad_id="noradId=12345",
                id="id=87",
                msg_epoch="msgEpoch=2004-09-28T02:49:00.000Z",
                insert_epoch="insertEpoch=2004-09-28T02:49:00.000Z",
                decay_epoch="decayEpoch=2004-09-28T02:49:00.000Z",
                window="window=900",
                rev="rev=25952",
                direction="direction=descending",
                latitude="latitude=36.0",
                longitude="longitude=217.5",
                inclination="inclination=53.0",
                next_report="decayEpoch=48",
                high_interest="highInterest=Y",
                format="json",
            )
            async for chunk in response:
                yield chunk


        asyncio.run(main())
        """
        async with self._raw_client.stream(
            norad_id=norad_id,
            id=id,
            msg_epoch=msg_epoch,
            insert_epoch=insert_epoch,
            decay_epoch=decay_epoch,
            window=window,
            rev=rev,
            direction=direction,
            latitude=latitude,
            longitude=longitude,
            inclination=inclination,
            next_report=next_report,
            high_interest=high_interest,
            format=format,
            size=size,
            page=page,
            request_options=request_options,
        ) as r:
            async for _chunk in r.data:
                yield _chunk
