# This file was auto-generated by Fern from our API Definition.

import contextlib
import json
import typing
from json.decoder import JSONDecodeError

from ...core.api_error import ApiError
from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.http_response import AsyncHttpResponse, HttpResponse
from ...core.parse_error import ParsingError
from ...core.request_options import RequestOptions
from ...core.unchecked_base_model import construct_type
from ..errors.bad_gateway_error import BadGatewayError
from ..errors.bad_request_error import BadRequestError
from ..errors.expectation_failed_error import ExpectationFailedError
from ..errors.forbidden_error import ForbiddenError
from ..errors.internal_server_error import InternalServerError
from ..errors.method_not_allowed_error import MethodNotAllowedError
from ..errors.not_found_error import NotFoundError
from ..errors.service_unavailable_error import ServiceUnavailableError
from ..errors.too_many_requests_error import TooManyRequestsError
from ..errors.unauthorized_error import UnauthorizedError
from ..types.error_response import ErrorResponse
from pydantic import ValidationError


class RawTipClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    @contextlib.contextmanager
    def stream(
        self,
        *,
        norad_id: typing.Optional[str] = None,
        id: typing.Optional[str] = None,
        msg_epoch: typing.Optional[str] = None,
        insert_epoch: typing.Optional[str] = None,
        decay_epoch: typing.Optional[str] = None,
        window: typing.Optional[str] = None,
        rev: typing.Optional[str] = None,
        direction: typing.Optional[str] = None,
        latitude: typing.Optional[str] = None,
        longitude: typing.Optional[str] = None,
        inclination: typing.Optional[str] = None,
        next_report: typing.Optional[str] = None,
        high_interest: typing.Optional[str] = None,
        format: typing.Optional[str] = None,
        size: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Iterator[HttpResponse[typing.Iterator[typing.Any]]]:
        """
        Find all TIP reports in the system or all reports that meet your search criteria defined by the query parameters

        Parameters
        ----------
        norad_id : typing.Optional[str]
            The noradId of an object. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        id : typing.Optional[str]
            The numeric id of the TIP report. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        msg_epoch : typing.Optional[str]
            Timestamp of when of the TIP report was produced. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), Between (=Value1...Value2)

        insert_epoch : typing.Optional[str]
            Timestamp of when the record was inserted in the system. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), Between (=Value1...Value2)

        decay_epoch : typing.Optional[str]
            Timestamp of the predicted time of atmospheric re-entry. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), Between (=Value1...Value2)

        window : typing.Optional[str]
            The uncertainty window around the re-entry time in seconds. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        rev : typing.Optional[str]
            The orbit revolution number at the time of prediction. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        direction : typing.Optional[str]
            The direction of orbital trajectory during re-entry prediction. Valid operators are: Equal (=Value), Not Equal (=<>Value), Like (=\\*Value), Not Like (=~*Value). Possible values: ascending and descending.

        latitude : typing.Optional[str]
            The latitude of predicted re-entry location. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        longitude : typing.Optional[str]
            Longitude of predicted re-entry location. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        inclination : typing.Optional[str]
            Inclination of the orbit at time of prediction. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        next_report : typing.Optional[str]
            Estimated time in hours until next update (Integer). Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        high_interest : typing.Optional[str]
            Flag indicating if object is considered high interest for re-entry tracking. Valid operators are: Equal (=Value), Not Equal (=<>Value), Like (=\\*Value), Not Like (=~*Value). Possible values: Y, N

        format : typing.Optional[str]
            Format of the request body. KVN, JSON, and XML are all valid formats. JSON is default.

        size : typing.Optional[int]
            Number of TIP Reports to return.

        page : typing.Optional[int]
            Page number for the queried TIP(s), indexed by 0 (first page). Default is 0

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.Iterator[HttpResponse[typing.Iterator[typing.Any]]]
            Ok - TIP(s) successfully retrieved.  Available formats are KVN (Text, Default), JSON, and XML.
        """
        with self._client_wrapper.httpx_client.stream(
            "bulkdata/tip/stream",
            method="GET",
            params={
                "noradId": norad_id,
                "id": id,
                "msgEpoch": msg_epoch,
                "insertEpoch": insert_epoch,
                "decayEpoch": decay_epoch,
                "window": window,
                "rev": rev,
                "direction": direction,
                "latitude": latitude,
                "longitude": longitude,
                "inclination": inclination,
                "nextReport": next_report,
                "highInterest": high_interest,
                "format": format,
                "size": size,
                "page": page,
            },
            request_options=request_options,
        ) as _response:

            def _stream() -> HttpResponse[typing.Iterator[typing.Any]]:
                try:
                    if 200 <= _response.status_code < 300:

                        def _iter():
                            for _text in _response.iter_lines():
                                try:
                                    if len(_text) == 0:
                                        continue
                                    yield typing.cast(
                                        typing.Any,
                                        construct_type(
                                            type_=typing.Any,  # type: ignore
                                            object_=json.loads(_text),
                                        ),
                                    )
                                except Exception:
                                    pass
                            return

                        return HttpResponse(response=_response, data=_iter())
                    _response.read()
                    if _response.status_code == 400:
                        raise BadRequestError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Any,
                                construct_type(
                                    type_=typing.Any,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 401:
                        raise UnauthorizedError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Any,
                                construct_type(
                                    type_=typing.Any,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 403:
                        raise ForbiddenError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Any,
                                construct_type(
                                    type_=typing.Any,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 404:
                        raise NotFoundError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Any,
                                construct_type(
                                    type_=typing.Any,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 405:
                        raise MethodNotAllowedError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Any,
                                construct_type(
                                    type_=typing.Any,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 417:
                        raise ExpectationFailedError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Any,
                                construct_type(
                                    type_=typing.Any,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 429:
                        raise TooManyRequestsError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Any,
                                construct_type(
                                    type_=typing.Any,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 500:
                        raise InternalServerError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Any,
                                construct_type(
                                    type_=typing.Any,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 502:
                        raise BadGatewayError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                ErrorResponse,
                                construct_type(
                                    type_=ErrorResponse,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 503:
                        raise ServiceUnavailableError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                ErrorResponse,
                                construct_type(
                                    type_=ErrorResponse,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    _response_json = _response.json()
                except JSONDecodeError:
                    raise ApiError(
                        status_code=_response.status_code,
                        headers=dict(_response.headers),
                        body=_response.text,
                    )
                except ValidationError as e:
                    raise ParsingError(
                        status_code=_response.status_code,
                        headers=dict(_response.headers),
                        body=_response.json(),
                        cause=e,
                    )
                raise ApiError(
                    status_code=_response.status_code,
                    headers=dict(_response.headers),
                    body=_response_json,
                )

            yield _stream()


class AsyncRawTipClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    @contextlib.asynccontextmanager
    async def stream(
        self,
        *,
        norad_id: typing.Optional[str] = None,
        id: typing.Optional[str] = None,
        msg_epoch: typing.Optional[str] = None,
        insert_epoch: typing.Optional[str] = None,
        decay_epoch: typing.Optional[str] = None,
        window: typing.Optional[str] = None,
        rev: typing.Optional[str] = None,
        direction: typing.Optional[str] = None,
        latitude: typing.Optional[str] = None,
        longitude: typing.Optional[str] = None,
        inclination: typing.Optional[str] = None,
        next_report: typing.Optional[str] = None,
        high_interest: typing.Optional[str] = None,
        format: typing.Optional[str] = None,
        size: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.AsyncIterator[AsyncHttpResponse[typing.AsyncIterator[typing.Any]]]:
        """
        Find all TIP reports in the system or all reports that meet your search criteria defined by the query parameters

        Parameters
        ----------
        norad_id : typing.Optional[str]
            The noradId of an object. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        id : typing.Optional[str]
            The numeric id of the TIP report. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        msg_epoch : typing.Optional[str]
            Timestamp of when of the TIP report was produced. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), Between (=Value1...Value2)

        insert_epoch : typing.Optional[str]
            Timestamp of when the record was inserted in the system. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), Between (=Value1...Value2)

        decay_epoch : typing.Optional[str]
            Timestamp of the predicted time of atmospheric re-entry. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), Between (=Value1...Value2)

        window : typing.Optional[str]
            The uncertainty window around the re-entry time in seconds. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        rev : typing.Optional[str]
            The orbit revolution number at the time of prediction. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        direction : typing.Optional[str]
            The direction of orbital trajectory during re-entry prediction. Valid operators are: Equal (=Value), Not Equal (=<>Value), Like (=\\*Value), Not Like (=~*Value). Possible values: ascending and descending.

        latitude : typing.Optional[str]
            The latitude of predicted re-entry location. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        longitude : typing.Optional[str]
            Longitude of predicted re-entry location. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        inclination : typing.Optional[str]
            Inclination of the orbit at time of prediction. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        next_report : typing.Optional[str]
            Estimated time in hours until next update (Integer). Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        high_interest : typing.Optional[str]
            Flag indicating if object is considered high interest for re-entry tracking. Valid operators are: Equal (=Value), Not Equal (=<>Value), Like (=\\*Value), Not Like (=~*Value). Possible values: Y, N

        format : typing.Optional[str]
            Format of the request body. KVN, JSON, and XML are all valid formats. JSON is default.

        size : typing.Optional[int]
            Number of TIP Reports to return.

        page : typing.Optional[int]
            Page number for the queried TIP(s), indexed by 0 (first page). Default is 0

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.AsyncIterator[AsyncHttpResponse[typing.AsyncIterator[typing.Any]]]
            Ok - TIP(s) successfully retrieved.  Available formats are KVN (Text, Default), JSON, and XML.
        """
        async with self._client_wrapper.httpx_client.stream(
            "bulkdata/tip/stream",
            method="GET",
            params={
                "noradId": norad_id,
                "id": id,
                "msgEpoch": msg_epoch,
                "insertEpoch": insert_epoch,
                "decayEpoch": decay_epoch,
                "window": window,
                "rev": rev,
                "direction": direction,
                "latitude": latitude,
                "longitude": longitude,
                "inclination": inclination,
                "nextReport": next_report,
                "highInterest": high_interest,
                "format": format,
                "size": size,
                "page": page,
            },
            request_options=request_options,
        ) as _response:

            async def _stream() -> AsyncHttpResponse[typing.AsyncIterator[typing.Any]]:
                try:
                    if 200 <= _response.status_code < 300:

                        async def _iter():
                            async for _text in _response.aiter_lines():
                                try:
                                    if len(_text) == 0:
                                        continue
                                    yield typing.cast(
                                        typing.Any,
                                        construct_type(
                                            type_=typing.Any,  # type: ignore
                                            object_=json.loads(_text),
                                        ),
                                    )
                                except Exception:
                                    pass
                            return

                        return AsyncHttpResponse(response=_response, data=_iter())
                    await _response.aread()
                    if _response.status_code == 400:
                        raise BadRequestError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Any,
                                construct_type(
                                    type_=typing.Any,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 401:
                        raise UnauthorizedError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Any,
                                construct_type(
                                    type_=typing.Any,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 403:
                        raise ForbiddenError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Any,
                                construct_type(
                                    type_=typing.Any,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 404:
                        raise NotFoundError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Any,
                                construct_type(
                                    type_=typing.Any,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 405:
                        raise MethodNotAllowedError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Any,
                                construct_type(
                                    type_=typing.Any,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 417:
                        raise ExpectationFailedError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Any,
                                construct_type(
                                    type_=typing.Any,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 429:
                        raise TooManyRequestsError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Any,
                                construct_type(
                                    type_=typing.Any,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 500:
                        raise InternalServerError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Any,
                                construct_type(
                                    type_=typing.Any,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 502:
                        raise BadGatewayError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                ErrorResponse,
                                construct_type(
                                    type_=ErrorResponse,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 503:
                        raise ServiceUnavailableError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                ErrorResponse,
                                construct_type(
                                    type_=ErrorResponse,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    _response_json = _response.json()
                except JSONDecodeError:
                    raise ApiError(
                        status_code=_response.status_code,
                        headers=dict(_response.headers),
                        body=_response.text,
                    )
                except ValidationError as e:
                    raise ParsingError(
                        status_code=_response.status_code,
                        headers=dict(_response.headers),
                        body=_response.json(),
                        cause=e,
                    )
                raise ApiError(
                    status_code=_response.status_code,
                    headers=dict(_response.headers),
                    body=_response_json,
                )

            yield await _stream()
