# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from .raw_client import AsyncRawTopicsClient, RawTopicsClient


class TopicsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawTopicsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawTopicsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawTopicsClient
        """
        return self._raw_client

    def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> str:
        """
        Retrieve the list of available topics to subscribe to, as well as their latest offset

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        str
            Ok - List of topics successfully retrieved

        Examples
        --------
        from tracss import TraCSS

        client = TraCSS(
            token="YOUR_TOKEN",
        )
        client.subscriber.topics.list()
        """
        _response = self._raw_client.list(request_options=request_options)
        return _response.data

    def get_offset(self, *, topic: str, request_options: typing.Optional[RequestOptions] = None) -> typing.Any:
        """
        Retrieve the latest kafka offset of a passed in topic

        Parameters
        ----------
        topic : str
            Topic to retrieve the offset from

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Ok - offset retrieved successfully

        Examples
        --------
        from tracss import TraCSS

        client = TraCSS(
            token="YOUR_TOKEN",
        )
        client.subscriber.topics.get_offset(
            topic="gov.tracss.tracss.v1.cdms",
        )
        """
        _response = self._raw_client.get_offset(topic=topic, request_options=request_options)
        return _response.data


class AsyncTopicsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawTopicsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawTopicsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawTopicsClient
        """
        return self._raw_client

    async def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> str:
        """
        Retrieve the list of available topics to subscribe to, as well as their latest offset

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        str
            Ok - List of topics successfully retrieved

        Examples
        --------
        import asyncio

        from tracss import AsyncTraCSS

        client = AsyncTraCSS(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.subscriber.topics.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(request_options=request_options)
        return _response.data

    async def get_offset(self, *, topic: str, request_options: typing.Optional[RequestOptions] = None) -> typing.Any:
        """
        Retrieve the latest kafka offset of a passed in topic

        Parameters
        ----------
        topic : str
            Topic to retrieve the offset from

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Ok - offset retrieved successfully

        Examples
        --------
        import asyncio

        from tracss import AsyncTraCSS

        client = AsyncTraCSS(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.subscriber.topics.get_offset(
                topic="gov.tracss.tracss.v1.cdms",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_offset(topic=topic, request_options=request_options)
        return _response.data
