# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .raw_client import AsyncRawSubscriberClient, RawSubscriberClient

if typing.TYPE_CHECKING:
    from .messages.client import AsyncMessagesClient, MessagesClient
    from .topics.client import AsyncTopicsClient, TopicsClient


class SubscriberClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSubscriberClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._topics: typing.Optional[TopicsClient] = None
        self._messages: typing.Optional[MessagesClient] = None

    @property
    def with_raw_response(self) -> RawSubscriberClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSubscriberClient
        """
        return self._raw_client

    @property
    def topics(self):
        if self._topics is None:
            from .topics.client import TopicsClient  # noqa: E402

            self._topics = TopicsClient(client_wrapper=self._client_wrapper)
        return self._topics

    @property
    def messages(self):
        if self._messages is None:
            from .messages.client import MessagesClient  # noqa: E402

            self._messages = MessagesClient(client_wrapper=self._client_wrapper)
        return self._messages


class AsyncSubscriberClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSubscriberClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._topics: typing.Optional[AsyncTopicsClient] = None
        self._messages: typing.Optional[AsyncMessagesClient] = None

    @property
    def with_raw_response(self) -> AsyncRawSubscriberClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSubscriberClient
        """
        return self._raw_client

    @property
    def topics(self):
        if self._topics is None:
            from .topics.client import AsyncTopicsClient  # noqa: E402

            self._topics = AsyncTopicsClient(client_wrapper=self._client_wrapper)
        return self._topics

    @property
    def messages(self):
        if self._messages is None:
            from .messages.client import AsyncMessagesClient  # noqa: E402

            self._messages = AsyncMessagesClient(client_wrapper=self._client_wrapper)
        return self._messages
