# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from .raw_client import AsyncRawAnnouncementsClient, RawAnnouncementsClient


class AnnouncementsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAnnouncementsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAnnouncementsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAnnouncementsClient
        """
        return self._raw_client

    def list(
        self,
        *,
        type: typing.Optional[str] = None,
        size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[typing.Dict[str, typing.Any]]:
        """
        Retrieve Space-Track Announcements that have been given to TraCSS

        Parameters
        ----------
        type : typing.Optional[str]
            Type/Criticality of Announcement.  Can be INFORMATION, OUTAGE, or EMERGENCY.

        size : typing.Optional[int]
            Number of results returned. A default of 0 will return all possible results.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[typing.Dict[str, typing.Any]]
            OK - Successfully retrieved the Announcement data. Returns a JSON array of Announcement objects.

        Examples
        --------
        from tracss import TraCSS

        client = TraCSS(
            client_id="YOUR_CLIENT_ID", client_secret="YOUR_CLIENT_SECRET",
        )
        client.bulk_data.announcements.list(
            type="EMERGENCY",
        )
        """
        _response = self._raw_client.list(
            type=type, size=size, request_options=request_options
        )
        return _response.data


class AsyncAnnouncementsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAnnouncementsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAnnouncementsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAnnouncementsClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        type: typing.Optional[str] = None,
        size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[typing.Dict[str, typing.Any]]:
        """
        Retrieve Space-Track Announcements that have been given to TraCSS

        Parameters
        ----------
        type : typing.Optional[str]
            Type/Criticality of Announcement.  Can be INFORMATION, OUTAGE, or EMERGENCY.

        size : typing.Optional[int]
            Number of results returned. A default of 0 will return all possible results.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[typing.Dict[str, typing.Any]]
            OK - Successfully retrieved the Announcement data. Returns a JSON array of Announcement objects.

        Examples
        --------
        import asyncio

        from tracss import AsyncTraCSS

        client = AsyncTraCSS(
            client_id="YOUR_CLIENT_ID", client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.bulk_data.announcements.list(
                type="EMERGENCY",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            type=type, size=size, request_options=request_options
        )
        return _response.data
