# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ..types.space_track import SpaceTrack
from ..types.space_track_nested_dto import SpaceTrackNestedDto
from .raw_client import AsyncRawSpaceTrackClient, RawSpaceTrackClient


class SpaceTrackClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSpaceTrackClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSpaceTrackClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSpaceTrackClient
        """
        return self._raw_client

    def list(
        self,
        *,
        id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Optional[typing.List[SpaceTrack]]:
        """
        Retrieves Space-track data based on a given correlationId

        Parameters
        ----------
        id : typing.Optional[str]
            Correlation Id (UUID) of the Space-Track data. If no id is provided, returns the names and correlationIds of all zip files we have received.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.List[SpaceTrack]]
            OK - Successfully retrieved the space tracks. Returns a JSON array of SpaceTrack objects.

        Examples
        --------
        from tracss import TraCSS

        client = TraCSS(
            client_id="YOUR_CLIENT_ID", client_secret="YOUR_CLIENT_SECRET",
        )
        client.metadata.space_track.list()
        """
        _response = self._raw_client.list(id=id, request_options=request_options)
        return _response.data

    def list_nested(
        self,
        *,
        id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[SpaceTrackNestedDto]:
        """
        Retrieve Space Track Package Data with all tar files combined in response

        Parameters
        ----------
        id : typing.Optional[str]
            Correlation Id (UUID) of the Space-Track data

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[SpaceTrackNestedDto]
            OK - Successfully retrieved the nested space track information. Returns a JSON array of SpaceTrackNestedDTO objects.

        Examples
        --------
        from tracss import TraCSS

        client = TraCSS(
            client_id="YOUR_CLIENT_ID", client_secret="YOUR_CLIENT_SECRET",
        )
        client.metadata.space_track.list_nested()
        """
        _response = self._raw_client.list_nested(id=id, request_options=request_options)
        return _response.data


class AsyncSpaceTrackClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSpaceTrackClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSpaceTrackClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSpaceTrackClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Optional[typing.List[SpaceTrack]]:
        """
        Retrieves Space-track data based on a given correlationId

        Parameters
        ----------
        id : typing.Optional[str]
            Correlation Id (UUID) of the Space-Track data. If no id is provided, returns the names and correlationIds of all zip files we have received.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.List[SpaceTrack]]
            OK - Successfully retrieved the space tracks. Returns a JSON array of SpaceTrack objects.

        Examples
        --------
        import asyncio

        from tracss import AsyncTraCSS

        client = AsyncTraCSS(
            client_id="YOUR_CLIENT_ID", client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.metadata.space_track.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(id=id, request_options=request_options)
        return _response.data

    async def list_nested(
        self,
        *,
        id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[SpaceTrackNestedDto]:
        """
        Retrieve Space Track Package Data with all tar files combined in response

        Parameters
        ----------
        id : typing.Optional[str]
            Correlation Id (UUID) of the Space-Track data

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[SpaceTrackNestedDto]
            OK - Successfully retrieved the nested space track information. Returns a JSON array of SpaceTrackNestedDTO objects.

        Examples
        --------
        import asyncio

        from tracss import AsyncTraCSS

        client = AsyncTraCSS(
            client_id="YOUR_CLIENT_ID", client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.metadata.space_track.list_nested()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_nested(
            id=id, request_options=request_options
        )
        return _response.data
