# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from .raw_client import AsyncRawTracssCatClient, RawTracssCatClient
from .types.list_tracss_cat_response import ListTracssCatResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class TracssCatClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawTracssCatClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawTracssCatClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawTracssCatClient
        """
        return self._raw_client

    def upload_csv(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.Any:
        """
        Upload a CSV file to update the TraCSS catalog. The CSV must include a noradId column as the minimum required header; all other fields are optional. Rows with noradIds your organization does not own will generate change requests pending TraCSS Operations approval. See tracss.gov for the full list of valid fields and accepted date formats.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            OK - Update request submitted successfully.

        Examples
        --------
        from tracss import TraCSS

        client = TraCSS(
            token="YOUR_TOKEN",
        )
        client.metadata.tracss_cat.upload_csv()
        """
        _response = self._raw_client.upload_csv(request_options=request_options)
        return _response.data

    def list(
        self,
        *,
        norad_id: typing.Optional[str] = None,
        satellite_name: typing.Optional[str] = None,
        organization: typing.Optional[str] = None,
        object_type: typing.Optional[str] = None,
        orbital_regime: typing.Optional[str] = None,
        count_only: typing.Optional[bool] = None,
        fields: typing.Optional[str] = None,
        headers_only: typing.Optional[bool] = None,
        sort: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListTracssCatResponse:
        """
        Retrieve one or more TraCSSCats based on query parameters. <b>All fields may be pre-pended with the following optional operators</b>: <br>Equal - (=Value) This is default and does not need to be included.
        <br>Not Equal (<>Value)
        <br>Greater Than (>Value)
        <br>Greater Than or Equal (>=Value)
        <br>Less Than (<Value)
        <br>Less Than or Equal (<=Value)
        <br>Like (\\*Value)
        <br>Not Like(~*Value)
        <p>Search parameters can also be a single value, or the following for searching a list or between values:
        <br>In (Value1,Value2) (list of comma separated values)
        <br>Between (Value1...Value2) (smaller value first)
        <br>
        <p>Note that if the field value is a String, it will perform a lexicographical comparison so operators like Less Than on Strings
        may return undesired results.

        Parameters
        ----------
        norad_id : typing.Optional[str]
            Norad ID, or list of comma separated ids, of the TracssCat object(s). A value with an optional operator that may be pre-pended to the value. Valid operators are: Greater Than (>Value), Less Than (<Value), Greater Than or Equal (>=Value), Less Than or Equal (<=Value), Not Equal (<>Value), In (Value1,Value2) , Between (Value1...Value2) (smaller value first), Like (\\*Value), Not Like(~*Value)

        satellite_name : typing.Optional[str]
            Name of the TracssCat object. A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2) , Between (Value1...Value2) (smaller value first), Like (\\*Value), Not Like(~*Value)

        organization : typing.Optional[str]
            Organization name, or list of comma separated organization names, responsible for the TracssCat object. A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2) , Like (\\*Value), Not Like(~*Value)

        object_type : typing.Optional[str]
            Object Type of the TracssCat(s) object. A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2) , Like (\\*Value), Not Like(~*Value)

        orbital_regime : typing.Optional[str]

        count_only : typing.Optional[bool]

        fields : typing.Optional[str]
            a comma separated list of fields to return a limited TraCSSCAT object

        headers_only : typing.Optional[bool]
            return only key fields from tracsscat in json format. Does not work with any filters

        sort : typing.Optional[str]
            Desired sort field and direction (Ascending = ASC, Descending = DESC), separated by a comma.

        page : typing.Optional[int]
            Page number for the queried TraCSSCat objects. Default is 0

        size : typing.Optional[int]
            Number of TraCSSCats per page.  Max is 5000

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListTracssCatResponse
            Ok - TracssCat(s) successfully retrieved.  Will return JSON representation of the object(s).

        Examples
        --------
        from tracss import TraCSS

        client = TraCSS(
            token="YOUR_TOKEN",
        )
        client.metadata.tracss_cat.list(
            norad_id="30580, or 30580,30581",
            satellite_name="THEMIS A",
            organization="nasa, or nasa,iridium",
            object_type="Payload",
            fields="noradId,objectType",
            sort="noradId,ASC",
        )
        """
        _response = self._raw_client.list(
            norad_id=norad_id,
            satellite_name=satellite_name,
            organization=organization,
            object_type=object_type,
            orbital_regime=orbital_regime,
            count_only=count_only,
            fields=fields,
            headers_only=headers_only,
            sort=sort,
            page=page,
            size=size,
            request_options=request_options,
        )
        return _response.data


class AsyncTracssCatClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawTracssCatClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawTracssCatClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawTracssCatClient
        """
        return self._raw_client

    async def upload_csv(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.Any:
        """
        Upload a CSV file to update the TraCSS catalog. The CSV must include a noradId column as the minimum required header; all other fields are optional. Rows with noradIds your organization does not own will generate change requests pending TraCSS Operations approval. See tracss.gov for the full list of valid fields and accepted date formats.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            OK - Update request submitted successfully.

        Examples
        --------
        import asyncio

        from tracss import AsyncTraCSS

        client = AsyncTraCSS(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.metadata.tracss_cat.upload_csv()


        asyncio.run(main())
        """
        _response = await self._raw_client.upload_csv(request_options=request_options)
        return _response.data

    async def list(
        self,
        *,
        norad_id: typing.Optional[str] = None,
        satellite_name: typing.Optional[str] = None,
        organization: typing.Optional[str] = None,
        object_type: typing.Optional[str] = None,
        orbital_regime: typing.Optional[str] = None,
        count_only: typing.Optional[bool] = None,
        fields: typing.Optional[str] = None,
        headers_only: typing.Optional[bool] = None,
        sort: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListTracssCatResponse:
        """
        Retrieve one or more TraCSSCats based on query parameters. <b>All fields may be pre-pended with the following optional operators</b>: <br>Equal - (=Value) This is default and does not need to be included.
        <br>Not Equal (<>Value)
        <br>Greater Than (>Value)
        <br>Greater Than or Equal (>=Value)
        <br>Less Than (<Value)
        <br>Less Than or Equal (<=Value)
        <br>Like (\\*Value)
        <br>Not Like(~*Value)
        <p>Search parameters can also be a single value, or the following for searching a list or between values:
        <br>In (Value1,Value2) (list of comma separated values)
        <br>Between (Value1...Value2) (smaller value first)
        <br>
        <p>Note that if the field value is a String, it will perform a lexicographical comparison so operators like Less Than on Strings
        may return undesired results.

        Parameters
        ----------
        norad_id : typing.Optional[str]
            Norad ID, or list of comma separated ids, of the TracssCat object(s). A value with an optional operator that may be pre-pended to the value. Valid operators are: Greater Than (>Value), Less Than (<Value), Greater Than or Equal (>=Value), Less Than or Equal (<=Value), Not Equal (<>Value), In (Value1,Value2) , Between (Value1...Value2) (smaller value first), Like (\\*Value), Not Like(~*Value)

        satellite_name : typing.Optional[str]
            Name of the TracssCat object. A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2) , Between (Value1...Value2) (smaller value first), Like (\\*Value), Not Like(~*Value)

        organization : typing.Optional[str]
            Organization name, or list of comma separated organization names, responsible for the TracssCat object. A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2) , Like (\\*Value), Not Like(~*Value)

        object_type : typing.Optional[str]
            Object Type of the TracssCat(s) object. A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2) , Like (\\*Value), Not Like(~*Value)

        orbital_regime : typing.Optional[str]

        count_only : typing.Optional[bool]

        fields : typing.Optional[str]
            a comma separated list of fields to return a limited TraCSSCAT object

        headers_only : typing.Optional[bool]
            return only key fields from tracsscat in json format. Does not work with any filters

        sort : typing.Optional[str]
            Desired sort field and direction (Ascending = ASC, Descending = DESC), separated by a comma.

        page : typing.Optional[int]
            Page number for the queried TraCSSCat objects. Default is 0

        size : typing.Optional[int]
            Number of TraCSSCats per page.  Max is 5000

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListTracssCatResponse
            Ok - TracssCat(s) successfully retrieved.  Will return JSON representation of the object(s).

        Examples
        --------
        import asyncio

        from tracss import AsyncTraCSS

        client = AsyncTraCSS(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.metadata.tracss_cat.list(
                norad_id="30580, or 30580,30581",
                satellite_name="THEMIS A",
                organization="nasa, or nasa,iridium",
                object_type="Payload",
                fields="noradId,objectType",
                sort="noradId,ASC",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            norad_id=norad_id,
            satellite_name=satellite_name,
            organization=organization,
            object_type=object_type,
            orbital_regime=orbital_regime,
            count_only=count_only,
            fields=fields,
            headers_only=headers_only,
            sort=sort,
            page=page,
            size=size,
            request_options=request_options,
        )
        return _response.data
