# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.serialization import FieldMetadata
from ...core.unchecked_base_model import UncheckedBaseModel


class ConjunctionCountSummary(UncheckedBaseModel):
    conjunction_data_event_total: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="conjunctionDataEventTotal"),
        pydantic.Field(alias="conjunctionDataEventTotal"),
    ] = None
    message_id_total: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="messageIdTotal"),
        pydantic.Field(alias="messageIdTotal"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
