# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.serialization import FieldMetadata
from ...core.unchecked_base_model import UncheckedBaseModel
from .conjunction_data_event_sat_list import ConjunctionDataEventSatList


class ConjunctionDataEventMain(UncheckedBaseModel):
    sats_at_risk: typing_extensions.Annotated[
        typing.Optional[typing.List[ConjunctionDataEventSatList]],
        FieldMetadata(alias="satsAtRisk"),
        pydantic.Field(alias="satsAtRisk"),
    ] = None
    total_sat_count: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="totalSatCount"),
        pydantic.Field(alias="totalSatCount"),
    ] = None
    page_size: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="pageSize"),
        pydantic.Field(alias="pageSize"),
    ] = None
    page: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
