# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.serialization import FieldMetadata
from ...core.unchecked_base_model import UncheckedBaseModel


class OperatorContactInfoByNoradIdDto(UncheckedBaseModel):
    """
    Operator contact information by NoradId
    """

    norad_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="noradId"),
        pydantic.Field(alias="noradId", description="Norad Id for Satellite"),
    ] = None
    organization: typing.Optional[str] = pydantic.Field(default=None)
    """
    Organization Name
    """

    operational_contact_names: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="operationalContactNames"),
        pydantic.Field(
            alias="operationalContactNames", description="Operational contact name(s)"
        ),
    ] = None
    operational_contact_emails: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="operationalContactEmails"),
        pydantic.Field(
            alias="operationalContactEmails", description="Operational contact email(s)"
        ),
    ] = None
    operational_contact_phones: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="operationalContactPhones"),
        pydantic.Field(
            alias="operationalContactPhones", description="Operational contact phone(s)"
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
