# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.serialization import FieldMetadata
from ...core.unchecked_base_model import UncheckedBaseModel


class SatelliteCharacteristicsDto(UncheckedBaseModel):
    norad_id: typing_extensions.Annotated[
        int, FieldMetadata(alias="noradId"), pydantic.Field(alias="noradId")
    ]
    satellite_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="satelliteName"),
        pydantic.Field(alias="satelliteName"),
    ] = None
    alternate_names: typing_extensions.Annotated[
        typing.Optional[typing.List[str]],
        FieldMetadata(alias="alternateNames"),
        pydantic.Field(alias="alternateNames"),
    ] = None
    international_designator: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="internationalDesignator"),
        pydantic.Field(alias="internationalDesignator"),
    ] = None
    organization: typing.Optional[str] = None
    country_of_launch_license: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="countryOfLaunchLicense"),
        pydantic.Field(alias="countryOfLaunchLicense"),
    ] = None
    country_providing_communication_license: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="countryProvidingCommunicationLicense"),
        pydantic.Field(alias="countryProvidingCommunicationLicense"),
    ] = None
    country_providing_remote_sensing: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="countryProvidingRemoteSensing"),
        pydantic.Field(alias="countryProvidingRemoteSensing"),
    ] = None
    country_of_un_registry: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="countryOfUNRegistry"),
        pydantic.Field(alias="countryOfUNRegistry"),
    ] = None
    constellation: typing.Optional[str] = None
    operational_status: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="operationalStatus"),
        pydantic.Field(alias="operationalStatus"),
    ] = None
    orbit_category: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="orbitCategory"),
        pydantic.Field(alias="orbitCategory"),
    ] = None
    wet_mass: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="wetMass"),
        pydantic.Field(alias="wetMass"),
    ] = None
    hard_body_radius: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="hardBodyRadius"),
        pydantic.Field(alias="hardBodyRadius"),
    ] = None
    conjunction_mitigation_capabilities: typing_extensions.Annotated[
        typing.Optional[typing.List[str]],
        FieldMetadata(alias="conjunctionMitigationCapabilities"),
        pydantic.Field(alias="conjunctionMitigationCapabilities"),
    ] = None
    expected_operational_mission_lifetime: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="expectedOperationalMissionLifetime"),
        pydantic.Field(alias="expectedOperationalMissionLifetime"),
    ] = None
    estimated_total_time_on_orbit: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="estimatedTotalTimeOnOrbit"),
        pydantic.Field(alias="estimatedTotalTimeOnOrbit"),
    ] = None
    launch_provider: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="launchProvider"),
        pydantic.Field(alias="launchProvider"),
    ] = None
    launch_vehicle: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="launchVehicle"),
        pydantic.Field(alias="launchVehicle"),
    ] = None
    launch_location: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="launchLocation"),
        pydantic.Field(alias="launchLocation"),
    ] = None
    launch_date: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="launchDate"),
        pydantic.Field(alias="launchDate"),
    ] = None
    deployment_date: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="deploymentDate"),
        pydantic.Field(alias="deploymentDate"),
    ] = None
    additional_deployments: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="additionalDeployments"),
        pydantic.Field(alias="additionalDeployments"),
    ] = None
    launch_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="launchName"),
        pydantic.Field(alias="launchName"),
    ] = None
    planned_orbit_period: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="plannedOrbitPeriod"),
        pydantic.Field(alias="plannedOrbitPeriod"),
    ] = None
    planned_orbit_inclination: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="plannedOrbitInclination"),
        pydantic.Field(alias="plannedOrbitInclination"),
    ] = None
    planned_orbit_apogee: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="plannedOrbitApogee"),
        pydantic.Field(alias="plannedOrbitApogee"),
    ] = None
    planned_orbit_perigee: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="plannedOrbitPerigee"),
        pydantic.Field(alias="plannedOrbitPerigee"),
    ] = None
    general_function: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="generalFunction"),
        pydantic.Field(alias="generalFunction"),
    ] = None
    object_type: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="objectType"),
        pydantic.Field(alias="objectType"),
    ] = None
    operational_contact_names: typing_extensions.Annotated[
        typing.Optional[typing.List[str]],
        FieldMetadata(alias="operationalContactNames"),
        pydantic.Field(alias="operationalContactNames"),
    ] = None
    operational_contact_emails: typing_extensions.Annotated[
        typing.Optional[typing.List[str]],
        FieldMetadata(alias="operationalContactEmails"),
        pydantic.Field(alias="operationalContactEmails"),
    ] = None
    operational_contact_phones: typing_extensions.Annotated[
        typing.Optional[typing.List[str]],
        FieldMetadata(alias="operationalContactPhones"),
        pydantic.Field(alias="operationalContactPhones"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
