# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.serialization import FieldMetadata
from ...core.unchecked_base_model import UncheckedBaseModel


class TracssCatHeaderDto(UncheckedBaseModel):
    object_type: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="objectType"),
        pydantic.Field(alias="objectType"),
    ] = None
    organization: typing.Optional[str] = None
    norad_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="noradId"),
        pydantic.Field(alias="noradId"),
    ] = None
    orbital_regime: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="orbitalRegime"),
        pydantic.Field(alias="orbitalRegime"),
    ] = None
    satellite_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="satelliteName"),
        pydantic.Field(alias="satelliteName"),
    ] = None
    international_designator: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="internationalDesignator"),
        pydantic.Field(alias="internationalDesignator"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
