# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2
from ....core.serialization import FieldMetadata
from ....core.unchecked_base_model import UncheckedBaseModel
from ...types.conjunction_data_event_dto import ConjunctionDataEventDto
from ...types.conjunction_data_event_header_dto import ConjunctionDataEventHeaderDto


class ListConjunctionEventsResponse(UncheckedBaseModel):
    headers_only: typing_extensions.Annotated[
        typing.Optional[typing.List[ConjunctionDataEventHeaderDto]],
        FieldMetadata(alias="headersOnly"),
        pydantic.Field(alias="headersOnly"),
    ] = None
    default: typing.Optional[typing.List[ConjunctionDataEventDto]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
