# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ...core.api_error import ApiError
from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.http_response import AsyncHttpResponse, HttpResponse
from ...core.parse_error import ParsingError
from ...core.request_options import RequestOptions
from ...core.unchecked_base_model import construct_type
from ..errors.bad_request_error import BadRequestError
from ..errors.internal_server_error import InternalServerError
from ..errors.unauthorized_error import UnauthorizedError
from pydantic import ValidationError


class RawTipReportsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(
        self,
        *,
        norad_id: typing.Optional[str] = None,
        id: typing.Optional[str] = None,
        msg_epoch: typing.Optional[str] = None,
        insert_epoch: typing.Optional[str] = None,
        decay_epoch: typing.Optional[str] = None,
        window: typing.Optional[str] = None,
        rev: typing.Optional[str] = None,
        direction: typing.Optional[str] = None,
        latitude: typing.Optional[str] = None,
        longitude: typing.Optional[str] = None,
        inclination: typing.Optional[str] = None,
        next_report: typing.Optional[str] = None,
        high_interest: typing.Optional[str] = None,
        fields: typing.Optional[str] = None,
        format: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[typing.Any]:
        """
        Find all TIP reports in the system or all reports that meet your search criteria defined by the query parameters.

        Parameters
        ----------
        norad_id : typing.Optional[str]
            The noradId of an object. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        id : typing.Optional[str]
            The numeric id of the TIP report. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        msg_epoch : typing.Optional[str]
            Timestamp of when of the TIP report was produced. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        insert_epoch : typing.Optional[str]
            Timestamp of when the record was inserted in the system. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        decay_epoch : typing.Optional[str]
            Timestamp of the predicted time of atmospheric re-entry. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        window : typing.Optional[str]
            The uncertainty window around the re-entry time in seconds. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        rev : typing.Optional[str]
            The orbit revolution number at the time of prediction. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        direction : typing.Optional[str]
            The direction of orbital trajectory during re-entry prediction. Valid operators are: Equal (=Value), Not Equal (=<>Value), Like (=*Value), Not Like (=~*Value). Possible values: ascending and descending.

        latitude : typing.Optional[str]
            The latitude of predicted re-entry location. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        longitude : typing.Optional[str]
            Longitude of predicted re-entry location. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        inclination : typing.Optional[str]
            Inclination of the orbit at time of prediction. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        next_report : typing.Optional[str]
            Estimated time in hours until next update (Integer). Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        high_interest : typing.Optional[str]
            Flag indicating if object is considered high interest for re-entry tracking. Valid operators are: Equal (=Value), Not Equal (=<>Value), Like (=*Value), Not Like (=~*Value). Possible values: Y, N

        fields : typing.Optional[str]
            Fields to return from TIP object. Valid fields are: Valid fields for JSON and XML include: NORAD_CAT_ID, MSG_EPOCH, INSERT_EPOCH, DECAY_EPOCH, WINDOW, REV, DIRECTION,
            LAT, LON, INCL, NEXT_REPORT, ID, HIGH_INTEREST.
            Regular KVN format does not support tuples.

        format : typing.Optional[str]
            Format of the request body. KVN, JSON, and XML are all valid formats. KVN is default.

        page : typing.Optional[int]
            Page number for queried TIP results. Default page is is 0

        size : typing.Optional[int]
            Number of TIP Reports per page.  Max and default value is 2147483647

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.Any]
            Ok - TIP(s) successfully retrieved.  Available formats are KVN (Text, Default), JSON, and XML.
        """
        _response = self._client_wrapper.httpx_client.request(
            "metadata/tipReports",
            method="GET",
            params={
                "noradId": norad_id,
                "id": id,
                "msgEpoch": msg_epoch,
                "insertEpoch": insert_epoch,
                "decayEpoch": decay_epoch,
                "window": window,
                "rev": rev,
                "direction": direction,
                "latitude": latitude,
                "longitude": longitude,
                "inclination": inclination,
                "nextReport": next_report,
                "highInterest": high_interest,
                "fields": fields,
                "format": format,
                "page": page,
                "size": size,
            },
            request_options=request_options,
        )
        try:
            if _response is None or not _response.text.strip():
                return HttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Any,
                    construct_type(
                        type_=typing.Any,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(
                status_code=_response.status_code,
                headers=dict(_response.headers),
                body=_response.text,
            )
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code,
                headers=dict(_response.headers),
                body=_response.json(),
                cause=e,
            )
        raise ApiError(
            status_code=_response.status_code,
            headers=dict(_response.headers),
            body=_response_json,
        )


class AsyncRawTipReportsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self,
        *,
        norad_id: typing.Optional[str] = None,
        id: typing.Optional[str] = None,
        msg_epoch: typing.Optional[str] = None,
        insert_epoch: typing.Optional[str] = None,
        decay_epoch: typing.Optional[str] = None,
        window: typing.Optional[str] = None,
        rev: typing.Optional[str] = None,
        direction: typing.Optional[str] = None,
        latitude: typing.Optional[str] = None,
        longitude: typing.Optional[str] = None,
        inclination: typing.Optional[str] = None,
        next_report: typing.Optional[str] = None,
        high_interest: typing.Optional[str] = None,
        fields: typing.Optional[str] = None,
        format: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[typing.Any]:
        """
        Find all TIP reports in the system or all reports that meet your search criteria defined by the query parameters.

        Parameters
        ----------
        norad_id : typing.Optional[str]
            The noradId of an object. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        id : typing.Optional[str]
            The numeric id of the TIP report. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        msg_epoch : typing.Optional[str]
            Timestamp of when of the TIP report was produced. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        insert_epoch : typing.Optional[str]
            Timestamp of when the record was inserted in the system. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        decay_epoch : typing.Optional[str]
            Timestamp of the predicted time of atmospheric re-entry. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        window : typing.Optional[str]
            The uncertainty window around the re-entry time in seconds. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        rev : typing.Optional[str]
            The orbit revolution number at the time of prediction. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        direction : typing.Optional[str]
            The direction of orbital trajectory during re-entry prediction. Valid operators are: Equal (=Value), Not Equal (=<>Value), Like (=*Value), Not Like (=~*Value). Possible values: ascending and descending.

        latitude : typing.Optional[str]
            The latitude of predicted re-entry location. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        longitude : typing.Optional[str]
            Longitude of predicted re-entry location. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        inclination : typing.Optional[str]
            Inclination of the orbit at time of prediction. Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        next_report : typing.Optional[str]
            Estimated time in hours until next update (Integer). Valid operators are: Equal (=Value), Not Equal (=<>Value), Greater Than or Equal (=>=Value), Greater Than (=>Value), Less Than or Equal (=<=Value), Less Than (=<Value), In (=Value1,Value2,etc), Between (=Value1...Value2)

        high_interest : typing.Optional[str]
            Flag indicating if object is considered high interest for re-entry tracking. Valid operators are: Equal (=Value), Not Equal (=<>Value), Like (=*Value), Not Like (=~*Value). Possible values: Y, N

        fields : typing.Optional[str]
            Fields to return from TIP object. Valid fields are: Valid fields for JSON and XML include: NORAD_CAT_ID, MSG_EPOCH, INSERT_EPOCH, DECAY_EPOCH, WINDOW, REV, DIRECTION,
            LAT, LON, INCL, NEXT_REPORT, ID, HIGH_INTEREST.
            Regular KVN format does not support tuples.

        format : typing.Optional[str]
            Format of the request body. KVN, JSON, and XML are all valid formats. KVN is default.

        page : typing.Optional[int]
            Page number for queried TIP results. Default page is is 0

        size : typing.Optional[int]
            Number of TIP Reports per page.  Max and default value is 2147483647

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.Any]
            Ok - TIP(s) successfully retrieved.  Available formats are KVN (Text, Default), JSON, and XML.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "metadata/tipReports",
            method="GET",
            params={
                "noradId": norad_id,
                "id": id,
                "msgEpoch": msg_epoch,
                "insertEpoch": insert_epoch,
                "decayEpoch": decay_epoch,
                "window": window,
                "rev": rev,
                "direction": direction,
                "latitude": latitude,
                "longitude": longitude,
                "inclination": inclination,
                "nextReport": next_report,
                "highInterest": high_interest,
                "fields": fields,
                "format": format,
                "page": page,
                "size": size,
            },
            request_options=request_options,
        )
        try:
            if _response is None or not _response.text.strip():
                return AsyncHttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Any,
                    construct_type(
                        type_=typing.Any,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(
                status_code=_response.status_code,
                headers=dict(_response.headers),
                body=_response.text,
            )
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code,
                headers=dict(_response.headers),
                body=_response.json(),
                cause=e,
            )
        raise ApiError(
            status_code=_response.status_code,
            headers=dict(_response.headers),
            body=_response_json,
        )
