# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from .raw_client import AsyncRawMessagesClient, RawMessagesClient
from .types.list_messages_response import ListMessagesResponse


class MessagesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawMessagesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawMessagesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawMessagesClient
        """
        return self._raw_client

    def list(
        self,
        *,
        topic: str,
        offset: str,
        max_results: typing.Optional[str] = None,
        filter_designators: typing.Optional[str] = None,
        fields: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListMessagesResponse:
        """
        Retrieve messages from a given topic starting at a given offset. Available topics are:                            gov.tracss.parsed.elsetCsv,                            gov.tracss.tracss.v1.cdms,                            gov.tracss.tracss.v2.cdms,                            gov.tracss.parsed.v1.ocms,                            gov.tracss.parsed.v2.ocms,                            gov.tracss.parsed.spVectors,                            gov.tracss.parsed.tracsscat                            gov.tracss.conjunction.data.event

        Parameters
        ----------
        topic : str
            Topic to retrieve messages from

        offset : str
            Offset to begin retrieving messages from - represents the starting point. Defaults to 0

        max_results : typing.Optional[str]
            Optional - max amount of messages to retrieve. If not provided, defaults to 1000, or 25 for gov.tracss.parsed.v1.ocms. This limits the number of results in the response - not number of messages looked at

        filter_designators : typing.Optional[str]
            Comma separated list of Object Designators to filter the request by. Can be combined with operators for more refined filtering.  Valid operators include:

            EQUALS (ie. filterDesignators=12345),

            NOT EQUALS (ie. filterDesignators=<>12345),

            LIKE (ie. filterDesignators=*123)  The like value can fall anywhere in the objectDesignator string,

            NOT LIKE(ie. filterDesignators=~*123)  The not like value can fall anywhere in the objectDesignator string,

            GREATER THAN OR EQUAL TO (ie. filterDesignators=>=12345),

            GREATER THAN (ie. filterDesignators=>12345),

            LESS THAN OR EQUAL TO (ie. filterDesignators=<=12345),

            LESS THAN (ie. filterDesignators=<12345),

            IN (ie. filterDesignators=12345,67890,34567)  Comma separated list of objectDesignators,

            BETWEEN (ie. filterDesignators=12345...67890) Lowest number in the range must be on the left.

        fields : typing.Optional[str]
            comma seperated list of fields to filter by. Only works with CDM and OCM topics

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListMessagesResponse
            Ok - messages retrieved successfully

        Examples
        --------
        from tracss import TraCSS

        client = TraCSS(
            token="YOUR_TOKEN",
        )
        client.subscriber.messages.list(
            topic="gov.tracss.tracss.v1.cdms",
            offset="offset",
            fields="missDistance, collisionProbability",
        )
        """
        _response = self._raw_client.list(
            topic=topic,
            offset=offset,
            max_results=max_results,
            filter_designators=filter_designators,
            fields=fields,
            request_options=request_options,
        )
        return _response.data


class AsyncMessagesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawMessagesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawMessagesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawMessagesClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        topic: str,
        offset: str,
        max_results: typing.Optional[str] = None,
        filter_designators: typing.Optional[str] = None,
        fields: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListMessagesResponse:
        """
        Retrieve messages from a given topic starting at a given offset. Available topics are:                            gov.tracss.parsed.elsetCsv,                            gov.tracss.tracss.v1.cdms,                            gov.tracss.tracss.v2.cdms,                            gov.tracss.parsed.v1.ocms,                            gov.tracss.parsed.v2.ocms,                            gov.tracss.parsed.spVectors,                            gov.tracss.parsed.tracsscat                            gov.tracss.conjunction.data.event

        Parameters
        ----------
        topic : str
            Topic to retrieve messages from

        offset : str
            Offset to begin retrieving messages from - represents the starting point. Defaults to 0

        max_results : typing.Optional[str]
            Optional - max amount of messages to retrieve. If not provided, defaults to 1000, or 25 for gov.tracss.parsed.v1.ocms. This limits the number of results in the response - not number of messages looked at

        filter_designators : typing.Optional[str]
            Comma separated list of Object Designators to filter the request by. Can be combined with operators for more refined filtering.  Valid operators include:

            EQUALS (ie. filterDesignators=12345),

            NOT EQUALS (ie. filterDesignators=<>12345),

            LIKE (ie. filterDesignators=*123)  The like value can fall anywhere in the objectDesignator string,

            NOT LIKE(ie. filterDesignators=~*123)  The not like value can fall anywhere in the objectDesignator string,

            GREATER THAN OR EQUAL TO (ie. filterDesignators=>=12345),

            GREATER THAN (ie. filterDesignators=>12345),

            LESS THAN OR EQUAL TO (ie. filterDesignators=<=12345),

            LESS THAN (ie. filterDesignators=<12345),

            IN (ie. filterDesignators=12345,67890,34567)  Comma separated list of objectDesignators,

            BETWEEN (ie. filterDesignators=12345...67890) Lowest number in the range must be on the left.

        fields : typing.Optional[str]
            comma seperated list of fields to filter by. Only works with CDM and OCM topics

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListMessagesResponse
            Ok - messages retrieved successfully

        Examples
        --------
        import asyncio

        from tracss import AsyncTraCSS

        client = AsyncTraCSS(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.subscriber.messages.list(
                topic="gov.tracss.tracss.v1.cdms",
                offset="offset",
                fields="missDistance, collisionProbability",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            topic=topic,
            offset=offset,
            max_results=max_results,
            filter_designators=filter_designators,
            fields=fields,
            request_options=request_options,
        )
        return _response.data
