# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from .raw_client import AsyncRawCdmClient, RawCdmClient
from .types.stream_cdm_response import StreamCdmResponse


class CdmClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawCdmClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawCdmClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawCdmClient
        """
        return self._raw_client

    def stream(
        self,
        *,
        message_id: typing.Optional[str] = None,
        correlation_id: typing.Optional[str] = None,
        tca: typing.Optional[str] = None,
        creation_date: typing.Optional[str] = None,
        message_for: typing.Optional[str] = None,
        screening_option: typing.Optional[str] = None,
        miss_distance: typing.Optional[str] = None,
        collision_probability: typing.Optional[str] = None,
        screen_volume_shape: typing.Optional[str] = None,
        object1type: typing.Optional[str] = None,
        object1object_designator: typing.Optional[str] = None,
        object1international_designator: typing.Optional[str] = None,
        object1operator_organization: typing.Optional[str] = None,
        object1ephemeris_name: typing.Optional[str] = None,
        object2type: typing.Optional[str] = None,
        object2object_designator: typing.Optional[str] = None,
        object2international_designator: typing.Optional[str] = None,
        object2operator_organization: typing.Optional[str] = None,
        object2ephemeris_name: typing.Optional[str] = None,
        headers_only: typing.Optional[bool] = None,
        size: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        format: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Iterator[StreamCdmResponse]:
        """
        Retrieve one or more TraCSS V2 CDMs from TRACSS cloud storage.

        Parameters
        ----------
        message_id : typing.Optional[str]
            Message Id (generated) from ASW that processed the CDM during super combo processing.A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        correlation_id : typing.Optional[str]
            Correlation Id (UUID) of the TraCSS CDM.A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        tca : typing.Optional[str]
            TCA (Time of Closest Approach).A value with an optional operator that may be pre-pended to the value. Valid operators are: Greater Than (>Value), Less Than (<Value), Greater Than or Equal (>=Value),Less Than or Equal (<=Value), Not Equal (<>Value) and Between (Value1...Value2) (smaller value first)

        creation_date : typing.Optional[str]
            Creation Date of the CDM.A value with an optional operator that may be pre-pended to the value. Valid operators are: Greater Than (>Value), Less Than (<Value), Greater Than or Equal (>=Value),Less Than or Equal (<=Value), Not Equal (<>Value) and Between (Value1...Value2) (smaller value first)

        message_for : typing.Optional[str]
            Name of Satellite whom the TraCSS cdm is for.A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        screening_option : typing.Optional[str]
            What was used during the screening process.A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        miss_distance : typing.Optional[str]
            The distance (in m) that object1 and object2 missed by. A value with an optional operator that may be pre-pended to the value. Valid operators are: Greater Than (>Value), Less Than (<Value), Greater Than or Equal (>=Value), Less Than or Equal (<=Value), Not Equal (<>Value), In (Value1,Value2) , Between (Value1...Value2) (smaller value first)

        collision_probability : typing.Optional[str]
            The probability of object1 and object2 having a collision.A value with an optional operator that may be pre-pended to the value. Valid operators are: Greater Than (>Value), Less Than (<Value), Greater Than or Equal (>=Value), Less Than or Equal (<=Value), Not Equal (<>Value), In (Value1,Value2) , Between (Value1...Value2) (smaller value first)

        screen_volume_shape : typing.Optional[str]
            The shape of the screen volume for object1A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object1type : typing.Optional[str]
            The object type of object1A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object1object_designator : typing.Optional[str]
            The designator for object1A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object1international_designator : typing.Optional[str]
            The international designator for object1A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object1operator_organization : typing.Optional[str]
            The operator organization for object1A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object1ephemeris_name : typing.Optional[str]
            The ephemeris name for object1A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object2type : typing.Optional[str]
            The object type of object2A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object2object_designator : typing.Optional[str]
            The designator for object2A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object2international_designator : typing.Optional[str]
            The international designator for object2A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object2operator_organization : typing.Optional[str]
            The operator organization for object2A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object2ephemeris_name : typing.Optional[str]
            The ephemeris name for object2A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        headers_only : typing.Optional[bool]
            Return a reduced object. The filters that work with headersOnly are: correlationId, creationDate, messageId, tca, missDistance, collisionProbability, object1ObjectDesignator, object2ObjectDesignator

        size : typing.Optional[int]
            Number of results to return.  Default of 0 means return all possible results.

        page : typing.Optional[int]
            Page number for the queried CDM(s), indexed by 0 (first page). Default is 0

        format : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.Iterator[StreamCdmResponse]
            NDJSON Stream for V2 CDMs

        Examples
        --------
        from tracss import TraCSS

        client = TraCSS(
            token="YOUR_TOKEN",
        )
        response = client.bulk_data.cdm.stream(
            message_id="000043928_conj_000054603_2024329195621",
            tca="2024-314T07:41:39.411",
            creation_date="2024-09-04T18:37:01Z",
            message_for="IRIDIUM 161",
            screening_option="Covariance",
            screen_volume_shape="Box, Ellipsoid, Deep Space",
            object1type="Payload",
            object1international_designator="2019-002A",
            object1operator_organization="Iridium",
            object1ephemeris_name="NONE",
            object2type="Payload",
            object2international_designator="2019-002A",
            object2operator_organization="Iridium",
            object2ephemeris_name="NONE",
        )
        for chunk in response:
            yield chunk
        """
        with self._raw_client.stream(
            message_id=message_id,
            correlation_id=correlation_id,
            tca=tca,
            creation_date=creation_date,
            message_for=message_for,
            screening_option=screening_option,
            miss_distance=miss_distance,
            collision_probability=collision_probability,
            screen_volume_shape=screen_volume_shape,
            object1type=object1type,
            object1object_designator=object1object_designator,
            object1international_designator=object1international_designator,
            object1operator_organization=object1operator_organization,
            object1ephemeris_name=object1ephemeris_name,
            object2type=object2type,
            object2object_designator=object2object_designator,
            object2international_designator=object2international_designator,
            object2operator_organization=object2operator_organization,
            object2ephemeris_name=object2ephemeris_name,
            headers_only=headers_only,
            size=size,
            page=page,
            format=format,
            request_options=request_options,
        ) as r:
            yield from r.data

    def stream_v1(
        self,
        *,
        message_id: typing.Optional[str] = None,
        correlation_id: typing.Optional[str] = None,
        tca: typing.Optional[str] = None,
        creation_date: typing.Optional[str] = None,
        message_for: typing.Optional[str] = None,
        screening_option: typing.Optional[str] = None,
        miss_distance: typing.Optional[str] = None,
        collision_probability: typing.Optional[str] = None,
        object1screen_volume_shape: typing.Optional[str] = None,
        object1type: typing.Optional[str] = None,
        object1object_designator: typing.Optional[str] = None,
        object1international_designator: typing.Optional[str] = None,
        object1operator_organization: typing.Optional[str] = None,
        object1ephemeris_name: typing.Optional[str] = None,
        object2screen_volume_shape: typing.Optional[str] = None,
        object2type: typing.Optional[str] = None,
        object2object_designator: typing.Optional[str] = None,
        object2international_designator: typing.Optional[str] = None,
        object2operator_organization: typing.Optional[str] = None,
        object2ephemeris_name: typing.Optional[str] = None,
        size: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        format: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Iterator[str]:
        """
        Retrieve one or more TraCSS V1 CDMs from TRACSS cloud storage.

        Parameters
        ----------
        message_id : typing.Optional[str]
            Message Id (generated) from ASW that processed the CDM during super combo processing.A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        correlation_id : typing.Optional[str]
            Correlation Id (UUID) of the TraCSS CDM.A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        tca : typing.Optional[str]
            TCA (Time of Closest Approach).A value with an optional operator that may be pre-pended to the value. Valid operators are: Greater Than (>Value), Less Than (<Value), Greater Than or Equal (>=Value),Less Than or Equal (<=Value), Not Equal (<>Value) and Between (Value1...Value2) (smaller value first)

        creation_date : typing.Optional[str]
            Creation Date of the CDM.A value with an optional operator that may be pre-pended to the value. Valid operators are: Greater Than (>Value), Less Than (<Value), Greater Than or Equal (>=Value),Less Than or Equal (<=Value), Not Equal (<>Value) and Between (Value1...Value2) (smaller value first)

        message_for : typing.Optional[str]
            Name of Satellite whom the TraCSS cdm is for.A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        screening_option : typing.Optional[str]
            What was used during the screening process.A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        miss_distance : typing.Optional[str]
            The distance (in m) that object1 and object2 missed by. A value with an optional operator that may be pre-pended to the value. Valid operators are: Greater Than (>Value), Less Than (<Value), Greater Than or Equal (>=Value), Less Than or Equal (<=Value), Not Equal (<>Value), In (Value1,Value2) , Between (Value1...Value2) (smaller value first)

        collision_probability : typing.Optional[str]
            The probability of object1 and object2 having a collision.A value with an optional operator that may be pre-pended to the value. Valid operators are: Greater Than (>Value), Less Than (<Value), Greater Than or Equal (>=Value), Less Than or Equal (<=Value), Not Equal (<>Value), In (Value1,Value2) , Between (Value1...Value2) (smaller value first)

        object1screen_volume_shape : typing.Optional[str]
            The shape of the screen volume for object1A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object1type : typing.Optional[str]
            The object type of object1A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object1object_designator : typing.Optional[str]
            The designator for object1A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object1international_designator : typing.Optional[str]
            The international designator for object1A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object1operator_organization : typing.Optional[str]
            The operator organization for object1A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object1ephemeris_name : typing.Optional[str]
            The ephemeris name for object1A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object2screen_volume_shape : typing.Optional[str]
            The shape of the screen volume for object2A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object2type : typing.Optional[str]
            The object type of object2A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object2object_designator : typing.Optional[str]
            The designator for object2A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object2international_designator : typing.Optional[str]
            The international designator for object2A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object2operator_organization : typing.Optional[str]
            The operator organization for object2A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object2ephemeris_name : typing.Optional[str]
            The ephemeris name for object2A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        size : typing.Optional[int]
            Number of results to return.  Default of 0 means return all possible results.

        page : typing.Optional[int]
            Page number for the queried CDM(s), indexed by 0 (first page). Default is 0

        format : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.Iterator[str]
            NDJSON Stream for V1 CDMs

        Examples
        --------
        from tracss import TraCSS

        client = TraCSS(
            token="YOUR_TOKEN",
        )
        response = client.bulk_data.cdm.stream_v1(
            message_id="000043928_conj_000054603_2024329195621",
            tca="2024-314T07:41:39.411",
            creation_date="2024-09-04T18:37:01Z",
            message_for="IRIDIUM 161",
            screening_option="Covariance",
            object1screen_volume_shape="Box, Ellipsoid, Deep Space",
            object1type="Payload",
            object1international_designator="2019-002A",
            object1operator_organization="Iridium",
            object1ephemeris_name="NONE",
            object2screen_volume_shape="Box, Ellipsoid, Deep Space",
            object2type="Payload",
            object2international_designator="2019-002A",
            object2operator_organization="Iridium",
            object2ephemeris_name="NONE",
        )
        for chunk in response:
            yield chunk
        """
        with self._raw_client.stream_v1(
            message_id=message_id,
            correlation_id=correlation_id,
            tca=tca,
            creation_date=creation_date,
            message_for=message_for,
            screening_option=screening_option,
            miss_distance=miss_distance,
            collision_probability=collision_probability,
            object1screen_volume_shape=object1screen_volume_shape,
            object1type=object1type,
            object1object_designator=object1object_designator,
            object1international_designator=object1international_designator,
            object1operator_organization=object1operator_organization,
            object1ephemeris_name=object1ephemeris_name,
            object2screen_volume_shape=object2screen_volume_shape,
            object2type=object2type,
            object2object_designator=object2object_designator,
            object2international_designator=object2international_designator,
            object2operator_organization=object2operator_organization,
            object2ephemeris_name=object2ephemeris_name,
            size=size,
            page=page,
            format=format,
            request_options=request_options,
        ) as r:
            yield from r.data


class AsyncCdmClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawCdmClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawCdmClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawCdmClient
        """
        return self._raw_client

    async def stream(
        self,
        *,
        message_id: typing.Optional[str] = None,
        correlation_id: typing.Optional[str] = None,
        tca: typing.Optional[str] = None,
        creation_date: typing.Optional[str] = None,
        message_for: typing.Optional[str] = None,
        screening_option: typing.Optional[str] = None,
        miss_distance: typing.Optional[str] = None,
        collision_probability: typing.Optional[str] = None,
        screen_volume_shape: typing.Optional[str] = None,
        object1type: typing.Optional[str] = None,
        object1object_designator: typing.Optional[str] = None,
        object1international_designator: typing.Optional[str] = None,
        object1operator_organization: typing.Optional[str] = None,
        object1ephemeris_name: typing.Optional[str] = None,
        object2type: typing.Optional[str] = None,
        object2object_designator: typing.Optional[str] = None,
        object2international_designator: typing.Optional[str] = None,
        object2operator_organization: typing.Optional[str] = None,
        object2ephemeris_name: typing.Optional[str] = None,
        headers_only: typing.Optional[bool] = None,
        size: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        format: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.AsyncIterator[StreamCdmResponse]:
        """
        Retrieve one or more TraCSS V2 CDMs from TRACSS cloud storage.

        Parameters
        ----------
        message_id : typing.Optional[str]
            Message Id (generated) from ASW that processed the CDM during super combo processing.A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        correlation_id : typing.Optional[str]
            Correlation Id (UUID) of the TraCSS CDM.A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        tca : typing.Optional[str]
            TCA (Time of Closest Approach).A value with an optional operator that may be pre-pended to the value. Valid operators are: Greater Than (>Value), Less Than (<Value), Greater Than or Equal (>=Value),Less Than or Equal (<=Value), Not Equal (<>Value) and Between (Value1...Value2) (smaller value first)

        creation_date : typing.Optional[str]
            Creation Date of the CDM.A value with an optional operator that may be pre-pended to the value. Valid operators are: Greater Than (>Value), Less Than (<Value), Greater Than or Equal (>=Value),Less Than or Equal (<=Value), Not Equal (<>Value) and Between (Value1...Value2) (smaller value first)

        message_for : typing.Optional[str]
            Name of Satellite whom the TraCSS cdm is for.A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        screening_option : typing.Optional[str]
            What was used during the screening process.A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        miss_distance : typing.Optional[str]
            The distance (in m) that object1 and object2 missed by. A value with an optional operator that may be pre-pended to the value. Valid operators are: Greater Than (>Value), Less Than (<Value), Greater Than or Equal (>=Value), Less Than or Equal (<=Value), Not Equal (<>Value), In (Value1,Value2) , Between (Value1...Value2) (smaller value first)

        collision_probability : typing.Optional[str]
            The probability of object1 and object2 having a collision.A value with an optional operator that may be pre-pended to the value. Valid operators are: Greater Than (>Value), Less Than (<Value), Greater Than or Equal (>=Value), Less Than or Equal (<=Value), Not Equal (<>Value), In (Value1,Value2) , Between (Value1...Value2) (smaller value first)

        screen_volume_shape : typing.Optional[str]
            The shape of the screen volume for object1A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object1type : typing.Optional[str]
            The object type of object1A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object1object_designator : typing.Optional[str]
            The designator for object1A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object1international_designator : typing.Optional[str]
            The international designator for object1A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object1operator_organization : typing.Optional[str]
            The operator organization for object1A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object1ephemeris_name : typing.Optional[str]
            The ephemeris name for object1A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object2type : typing.Optional[str]
            The object type of object2A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object2object_designator : typing.Optional[str]
            The designator for object2A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object2international_designator : typing.Optional[str]
            The international designator for object2A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object2operator_organization : typing.Optional[str]
            The operator organization for object2A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object2ephemeris_name : typing.Optional[str]
            The ephemeris name for object2A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        headers_only : typing.Optional[bool]
            Return a reduced object. The filters that work with headersOnly are: correlationId, creationDate, messageId, tca, missDistance, collisionProbability, object1ObjectDesignator, object2ObjectDesignator

        size : typing.Optional[int]
            Number of results to return.  Default of 0 means return all possible results.

        page : typing.Optional[int]
            Page number for the queried CDM(s), indexed by 0 (first page). Default is 0

        format : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.AsyncIterator[StreamCdmResponse]
            NDJSON Stream for V2 CDMs

        Examples
        --------
        import asyncio

        from tracss import AsyncTraCSS

        client = AsyncTraCSS(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            response = await client.bulk_data.cdm.stream(
                message_id="000043928_conj_000054603_2024329195621",
                tca="2024-314T07:41:39.411",
                creation_date="2024-09-04T18:37:01Z",
                message_for="IRIDIUM 161",
                screening_option="Covariance",
                screen_volume_shape="Box, Ellipsoid, Deep Space",
                object1type="Payload",
                object1international_designator="2019-002A",
                object1operator_organization="Iridium",
                object1ephemeris_name="NONE",
                object2type="Payload",
                object2international_designator="2019-002A",
                object2operator_organization="Iridium",
                object2ephemeris_name="NONE",
            )
            async for chunk in response:
                yield chunk


        asyncio.run(main())
        """
        async with self._raw_client.stream(
            message_id=message_id,
            correlation_id=correlation_id,
            tca=tca,
            creation_date=creation_date,
            message_for=message_for,
            screening_option=screening_option,
            miss_distance=miss_distance,
            collision_probability=collision_probability,
            screen_volume_shape=screen_volume_shape,
            object1type=object1type,
            object1object_designator=object1object_designator,
            object1international_designator=object1international_designator,
            object1operator_organization=object1operator_organization,
            object1ephemeris_name=object1ephemeris_name,
            object2type=object2type,
            object2object_designator=object2object_designator,
            object2international_designator=object2international_designator,
            object2operator_organization=object2operator_organization,
            object2ephemeris_name=object2ephemeris_name,
            headers_only=headers_only,
            size=size,
            page=page,
            format=format,
            request_options=request_options,
        ) as r:
            async for _chunk in r.data:
                yield _chunk

    async def stream_v1(
        self,
        *,
        message_id: typing.Optional[str] = None,
        correlation_id: typing.Optional[str] = None,
        tca: typing.Optional[str] = None,
        creation_date: typing.Optional[str] = None,
        message_for: typing.Optional[str] = None,
        screening_option: typing.Optional[str] = None,
        miss_distance: typing.Optional[str] = None,
        collision_probability: typing.Optional[str] = None,
        object1screen_volume_shape: typing.Optional[str] = None,
        object1type: typing.Optional[str] = None,
        object1object_designator: typing.Optional[str] = None,
        object1international_designator: typing.Optional[str] = None,
        object1operator_organization: typing.Optional[str] = None,
        object1ephemeris_name: typing.Optional[str] = None,
        object2screen_volume_shape: typing.Optional[str] = None,
        object2type: typing.Optional[str] = None,
        object2object_designator: typing.Optional[str] = None,
        object2international_designator: typing.Optional[str] = None,
        object2operator_organization: typing.Optional[str] = None,
        object2ephemeris_name: typing.Optional[str] = None,
        size: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        format: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.AsyncIterator[str]:
        """
        Retrieve one or more TraCSS V1 CDMs from TRACSS cloud storage.

        Parameters
        ----------
        message_id : typing.Optional[str]
            Message Id (generated) from ASW that processed the CDM during super combo processing.A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        correlation_id : typing.Optional[str]
            Correlation Id (UUID) of the TraCSS CDM.A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        tca : typing.Optional[str]
            TCA (Time of Closest Approach).A value with an optional operator that may be pre-pended to the value. Valid operators are: Greater Than (>Value), Less Than (<Value), Greater Than or Equal (>=Value),Less Than or Equal (<=Value), Not Equal (<>Value) and Between (Value1...Value2) (smaller value first)

        creation_date : typing.Optional[str]
            Creation Date of the CDM.A value with an optional operator that may be pre-pended to the value. Valid operators are: Greater Than (>Value), Less Than (<Value), Greater Than or Equal (>=Value),Less Than or Equal (<=Value), Not Equal (<>Value) and Between (Value1...Value2) (smaller value first)

        message_for : typing.Optional[str]
            Name of Satellite whom the TraCSS cdm is for.A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        screening_option : typing.Optional[str]
            What was used during the screening process.A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        miss_distance : typing.Optional[str]
            The distance (in m) that object1 and object2 missed by. A value with an optional operator that may be pre-pended to the value. Valid operators are: Greater Than (>Value), Less Than (<Value), Greater Than or Equal (>=Value), Less Than or Equal (<=Value), Not Equal (<>Value), In (Value1,Value2) , Between (Value1...Value2) (smaller value first)

        collision_probability : typing.Optional[str]
            The probability of object1 and object2 having a collision.A value with an optional operator that may be pre-pended to the value. Valid operators are: Greater Than (>Value), Less Than (<Value), Greater Than or Equal (>=Value), Less Than or Equal (<=Value), Not Equal (<>Value), In (Value1,Value2) , Between (Value1...Value2) (smaller value first)

        object1screen_volume_shape : typing.Optional[str]
            The shape of the screen volume for object1A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object1type : typing.Optional[str]
            The object type of object1A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object1object_designator : typing.Optional[str]
            The designator for object1A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object1international_designator : typing.Optional[str]
            The international designator for object1A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object1operator_organization : typing.Optional[str]
            The operator organization for object1A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object1ephemeris_name : typing.Optional[str]
            The ephemeris name for object1A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object2screen_volume_shape : typing.Optional[str]
            The shape of the screen volume for object2A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object2type : typing.Optional[str]
            The object type of object2A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object2object_designator : typing.Optional[str]
            The designator for object2A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object2international_designator : typing.Optional[str]
            The international designator for object2A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object2operator_organization : typing.Optional[str]
            The operator organization for object2A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object2ephemeris_name : typing.Optional[str]
            The ephemeris name for object2A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        size : typing.Optional[int]
            Number of results to return.  Default of 0 means return all possible results.

        page : typing.Optional[int]
            Page number for the queried CDM(s), indexed by 0 (first page). Default is 0

        format : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.AsyncIterator[str]
            NDJSON Stream for V1 CDMs

        Examples
        --------
        import asyncio

        from tracss import AsyncTraCSS

        client = AsyncTraCSS(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            response = await client.bulk_data.cdm.stream_v1(
                message_id="000043928_conj_000054603_2024329195621",
                tca="2024-314T07:41:39.411",
                creation_date="2024-09-04T18:37:01Z",
                message_for="IRIDIUM 161",
                screening_option="Covariance",
                object1screen_volume_shape="Box, Ellipsoid, Deep Space",
                object1type="Payload",
                object1international_designator="2019-002A",
                object1operator_organization="Iridium",
                object1ephemeris_name="NONE",
                object2screen_volume_shape="Box, Ellipsoid, Deep Space",
                object2type="Payload",
                object2international_designator="2019-002A",
                object2operator_organization="Iridium",
                object2ephemeris_name="NONE",
            )
            async for chunk in response:
                yield chunk


        asyncio.run(main())
        """
        async with self._raw_client.stream_v1(
            message_id=message_id,
            correlation_id=correlation_id,
            tca=tca,
            creation_date=creation_date,
            message_for=message_for,
            screening_option=screening_option,
            miss_distance=miss_distance,
            collision_probability=collision_probability,
            object1screen_volume_shape=object1screen_volume_shape,
            object1type=object1type,
            object1object_designator=object1object_designator,
            object1international_designator=object1international_designator,
            object1operator_organization=object1operator_organization,
            object1ephemeris_name=object1ephemeris_name,
            object2screen_volume_shape=object2screen_volume_shape,
            object2type=object2type,
            object2object_designator=object2object_designator,
            object2international_designator=object2international_designator,
            object2operator_organization=object2operator_organization,
            object2ephemeris_name=object2ephemeris_name,
            size=size,
            page=page,
            format=format,
            request_options=request_options,
        ) as r:
            async for _chunk in r.data:
                yield _chunk
