# This file was auto-generated by Fern from our API Definition.

import contextlib
import json
import typing
from json.decoder import JSONDecodeError

from ...core.api_error import ApiError
from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.http_response import AsyncHttpResponse, HttpResponse
from ...core.parse_error import ParsingError
from ...core.request_options import RequestOptions
from ...core.unchecked_base_model import construct_type
from ..errors.bad_gateway_error import BadGatewayError
from ..errors.bad_request_error import BadRequestError
from ..errors.expectation_failed_error import ExpectationFailedError
from ..errors.forbidden_error import ForbiddenError
from ..errors.internal_server_error import InternalServerError
from ..errors.method_not_allowed_error import MethodNotAllowedError
from ..errors.not_found_error import NotFoundError
from ..errors.service_unavailable_error import ServiceUnavailableError
from ..errors.too_many_requests_error import TooManyRequestsError
from ..errors.unauthorized_error import UnauthorizedError
from ..types.error_response import ErrorResponse
from .types.stream_cdm_response import StreamCdmResponse
from pydantic import ValidationError


class RawCdmClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    @contextlib.contextmanager
    def stream(
        self,
        *,
        message_id: typing.Optional[str] = None,
        correlation_id: typing.Optional[str] = None,
        tca: typing.Optional[str] = None,
        creation_date: typing.Optional[str] = None,
        message_for: typing.Optional[str] = None,
        screening_option: typing.Optional[str] = None,
        miss_distance: typing.Optional[str] = None,
        collision_probability: typing.Optional[str] = None,
        screen_volume_shape: typing.Optional[str] = None,
        object1type: typing.Optional[str] = None,
        object1object_designator: typing.Optional[str] = None,
        object1international_designator: typing.Optional[str] = None,
        object1operator_organization: typing.Optional[str] = None,
        object1ephemeris_name: typing.Optional[str] = None,
        object2type: typing.Optional[str] = None,
        object2object_designator: typing.Optional[str] = None,
        object2international_designator: typing.Optional[str] = None,
        object2operator_organization: typing.Optional[str] = None,
        object2ephemeris_name: typing.Optional[str] = None,
        headers_only: typing.Optional[bool] = None,
        size: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        format: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Iterator[HttpResponse[typing.Iterator[StreamCdmResponse]]]:
        """
        Retrieve CDMs generated by TraCSS


        Example Scripts:


        | Guide                                                              | Script                                                                 |
        |--------------------------------------------------------------------|------------------------------------------------------------------------|
        | [Pull Bulk CDMs Guide](/bulkdata/scripts/README_pull_bulk_cdms.md) | [Pull Bulk CDMs Script (Python)](/bulkdata/scripts/pull_bulk_cdms.py)  |


        Parameters
        ----------
        message_id : typing.Optional[str]
            Message Id (generated) from ASW that processed the CDM during super combo processing.A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        correlation_id : typing.Optional[str]
            Correlation Id (UUID) of the TraCSS CDM.A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        tca : typing.Optional[str]
            TCA (Time of Closest Approach).A value with an optional operator that may be pre-pended to the value. Valid operators are: Greater Than (>Value), Less Than (<Value), Greater Than or Equal (>=Value),Less Than or Equal (<=Value), Not Equal (<>Value) and Between (Value1...Value2) (smaller value first)

        creation_date : typing.Optional[str]
            Creation Date of the CDM.A value with an optional operator that may be pre-pended to the value. Valid operators are: Greater Than (>Value), Less Than (<Value), Greater Than or Equal (>=Value),Less Than or Equal (<=Value), Not Equal (<>Value) and Between (Value1...Value2) (smaller value first)

        message_for : typing.Optional[str]
            Name of Satellite whom the TraCSS cdm is for.A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        screening_option : typing.Optional[str]
            What was used during the screening process.A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        miss_distance : typing.Optional[str]
            The distance (in m) that object1 and object2 missed by. A value with an optional operator that may be pre-pended to the value. Valid operators are: Greater Than (>Value), Less Than (<Value), Greater Than or Equal (>=Value), Less Than or Equal (<=Value), Not Equal (<>Value), In (Value1,Value2) , Between (Value1...Value2) (smaller value first)

        collision_probability : typing.Optional[str]
            The probability of object1 and object2 having a collision.A value with an optional operator that may be pre-pended to the value. Valid operators are: Greater Than (>Value), Less Than (<Value), Greater Than or Equal (>=Value), Less Than or Equal (<=Value), Not Equal (<>Value), In (Value1,Value2) , Between (Value1...Value2) (smaller value first)

        screen_volume_shape : typing.Optional[str]
            The shape of the screen volume for object1A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object1type : typing.Optional[str]
            The object type of object1A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object1object_designator : typing.Optional[str]
            The designator for object1A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object1international_designator : typing.Optional[str]
            The international designator for object1A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object1operator_organization : typing.Optional[str]
            The operator organization for object1A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object1ephemeris_name : typing.Optional[str]
            The ephemeris name for object1A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object2type : typing.Optional[str]
            The object type of object2A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object2object_designator : typing.Optional[str]
            The designator for object2A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object2international_designator : typing.Optional[str]
            The international designator for object2A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object2operator_organization : typing.Optional[str]
            The operator organization for object2A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object2ephemeris_name : typing.Optional[str]
            The ephemeris name for object2A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        headers_only : typing.Optional[bool]
            Return a reduced object. The filters that work with headersOnly are: correlationId, creationDate, messageId, tca, missDistance, collisionProbability, object1ObjectDesignator, object2ObjectDesignator

        size : typing.Optional[int]
            Number of results to return.  Default of 0 means return all possible results.

        page : typing.Optional[int]
            Page number for the queried CDM(s), indexed by 0 (first page). Default is 0

        format : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.Iterator[HttpResponse[typing.Iterator[StreamCdmResponse]]]
            NDJSON Stream for V2 CDMs
        """
        with self._client_wrapper.httpx_client.stream(
            "bulkdata/cdm/v2/stream",
            method="GET",
            params={
                "messageId": message_id,
                "correlationId": correlation_id,
                "tca": tca,
                "creationDate": creation_date,
                "messageFor": message_for,
                "screeningOption": screening_option,
                "missDistance": miss_distance,
                "collisionProbability": collision_probability,
                "screenVolumeShape": screen_volume_shape,
                "object1Type": object1type,
                "object1ObjectDesignator": object1object_designator,
                "object1InternationalDesignator": object1international_designator,
                "object1OperatorOrganization": object1operator_organization,
                "object1EphemerisName": object1ephemeris_name,
                "object2Type": object2type,
                "object2ObjectDesignator": object2object_designator,
                "object2InternationalDesignator": object2international_designator,
                "object2OperatorOrganization": object2operator_organization,
                "object2EphemerisName": object2ephemeris_name,
                "headersOnly": headers_only,
                "size": size,
                "page": page,
                "format": format,
            },
            request_options=request_options,
        ) as _response:

            def _stream() -> HttpResponse[typing.Iterator[StreamCdmResponse]]:
                try:
                    if 200 <= _response.status_code < 300:

                        def _iter():
                            for _text in _response.iter_lines():
                                try:
                                    if len(_text) == 0:
                                        continue
                                    yield typing.cast(
                                        StreamCdmResponse,
                                        construct_type(
                                            type_=StreamCdmResponse,  # type: ignore
                                            object_=json.loads(_text),
                                        ),
                                    )
                                except Exception:
                                    pass
                            return

                        return HttpResponse(response=_response, data=_iter())
                    _response.read()
                    if _response.status_code == 400:
                        raise BadRequestError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Any,
                                construct_type(
                                    type_=typing.Any,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 401:
                        raise UnauthorizedError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Any,
                                construct_type(
                                    type_=typing.Any,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 403:
                        raise ForbiddenError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Any,
                                construct_type(
                                    type_=typing.Any,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 404:
                        raise NotFoundError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Any,
                                construct_type(
                                    type_=typing.Any,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 405:
                        raise MethodNotAllowedError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Any,
                                construct_type(
                                    type_=typing.Any,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 417:
                        raise ExpectationFailedError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Any,
                                construct_type(
                                    type_=typing.Any,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 429:
                        raise TooManyRequestsError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Any,
                                construct_type(
                                    type_=typing.Any,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 500:
                        raise InternalServerError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Any,
                                construct_type(
                                    type_=typing.Any,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 502:
                        raise BadGatewayError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                ErrorResponse,
                                construct_type(
                                    type_=ErrorResponse,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 503:
                        raise ServiceUnavailableError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                ErrorResponse,
                                construct_type(
                                    type_=ErrorResponse,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    _response_json = _response.json()
                except JSONDecodeError:
                    raise ApiError(
                        status_code=_response.status_code,
                        headers=dict(_response.headers),
                        body=_response.text,
                    )
                except ValidationError as e:
                    raise ParsingError(
                        status_code=_response.status_code,
                        headers=dict(_response.headers),
                        body=_response.json(),
                        cause=e,
                    )
                raise ApiError(
                    status_code=_response.status_code,
                    headers=dict(_response.headers),
                    body=_response_json,
                )

            yield _stream()


class AsyncRawCdmClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    @contextlib.asynccontextmanager
    async def stream(
        self,
        *,
        message_id: typing.Optional[str] = None,
        correlation_id: typing.Optional[str] = None,
        tca: typing.Optional[str] = None,
        creation_date: typing.Optional[str] = None,
        message_for: typing.Optional[str] = None,
        screening_option: typing.Optional[str] = None,
        miss_distance: typing.Optional[str] = None,
        collision_probability: typing.Optional[str] = None,
        screen_volume_shape: typing.Optional[str] = None,
        object1type: typing.Optional[str] = None,
        object1object_designator: typing.Optional[str] = None,
        object1international_designator: typing.Optional[str] = None,
        object1operator_organization: typing.Optional[str] = None,
        object1ephemeris_name: typing.Optional[str] = None,
        object2type: typing.Optional[str] = None,
        object2object_designator: typing.Optional[str] = None,
        object2international_designator: typing.Optional[str] = None,
        object2operator_organization: typing.Optional[str] = None,
        object2ephemeris_name: typing.Optional[str] = None,
        headers_only: typing.Optional[bool] = None,
        size: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        format: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.AsyncIterator[AsyncHttpResponse[typing.AsyncIterator[StreamCdmResponse]]]:
        """
        Retrieve CDMs generated by TraCSS


        Example Scripts:


        | Guide                                                              | Script                                                                 |
        |--------------------------------------------------------------------|------------------------------------------------------------------------|
        | [Pull Bulk CDMs Guide](/bulkdata/scripts/README_pull_bulk_cdms.md) | [Pull Bulk CDMs Script (Python)](/bulkdata/scripts/pull_bulk_cdms.py)  |


        Parameters
        ----------
        message_id : typing.Optional[str]
            Message Id (generated) from ASW that processed the CDM during super combo processing.A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        correlation_id : typing.Optional[str]
            Correlation Id (UUID) of the TraCSS CDM.A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        tca : typing.Optional[str]
            TCA (Time of Closest Approach).A value with an optional operator that may be pre-pended to the value. Valid operators are: Greater Than (>Value), Less Than (<Value), Greater Than or Equal (>=Value),Less Than or Equal (<=Value), Not Equal (<>Value) and Between (Value1...Value2) (smaller value first)

        creation_date : typing.Optional[str]
            Creation Date of the CDM.A value with an optional operator that may be pre-pended to the value. Valid operators are: Greater Than (>Value), Less Than (<Value), Greater Than or Equal (>=Value),Less Than or Equal (<=Value), Not Equal (<>Value) and Between (Value1...Value2) (smaller value first)

        message_for : typing.Optional[str]
            Name of Satellite whom the TraCSS cdm is for.A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        screening_option : typing.Optional[str]
            What was used during the screening process.A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        miss_distance : typing.Optional[str]
            The distance (in m) that object1 and object2 missed by. A value with an optional operator that may be pre-pended to the value. Valid operators are: Greater Than (>Value), Less Than (<Value), Greater Than or Equal (>=Value), Less Than or Equal (<=Value), Not Equal (<>Value), In (Value1,Value2) , Between (Value1...Value2) (smaller value first)

        collision_probability : typing.Optional[str]
            The probability of object1 and object2 having a collision.A value with an optional operator that may be pre-pended to the value. Valid operators are: Greater Than (>Value), Less Than (<Value), Greater Than or Equal (>=Value), Less Than or Equal (<=Value), Not Equal (<>Value), In (Value1,Value2) , Between (Value1...Value2) (smaller value first)

        screen_volume_shape : typing.Optional[str]
            The shape of the screen volume for object1A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object1type : typing.Optional[str]
            The object type of object1A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object1object_designator : typing.Optional[str]
            The designator for object1A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object1international_designator : typing.Optional[str]
            The international designator for object1A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object1operator_organization : typing.Optional[str]
            The operator organization for object1A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object1ephemeris_name : typing.Optional[str]
            The ephemeris name for object1A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object2type : typing.Optional[str]
            The object type of object2A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object2object_designator : typing.Optional[str]
            The designator for object2A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object2international_designator : typing.Optional[str]
            The international designator for object2A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object2operator_organization : typing.Optional[str]
            The operator organization for object2A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        object2ephemeris_name : typing.Optional[str]
            The ephemeris name for object2A value with an optional operator that may be pre-pended to the value. Valid operators are: Not Equal (<>Value), In (Value1,Value2), Like (\\*Value), Not Like(~*Value)

        headers_only : typing.Optional[bool]
            Return a reduced object. The filters that work with headersOnly are: correlationId, creationDate, messageId, tca, missDistance, collisionProbability, object1ObjectDesignator, object2ObjectDesignator

        size : typing.Optional[int]
            Number of results to return.  Default of 0 means return all possible results.

        page : typing.Optional[int]
            Page number for the queried CDM(s), indexed by 0 (first page). Default is 0

        format : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.AsyncIterator[AsyncHttpResponse[typing.AsyncIterator[StreamCdmResponse]]]
            NDJSON Stream for V2 CDMs
        """
        async with self._client_wrapper.httpx_client.stream(
            "bulkdata/cdm/v2/stream",
            method="GET",
            params={
                "messageId": message_id,
                "correlationId": correlation_id,
                "tca": tca,
                "creationDate": creation_date,
                "messageFor": message_for,
                "screeningOption": screening_option,
                "missDistance": miss_distance,
                "collisionProbability": collision_probability,
                "screenVolumeShape": screen_volume_shape,
                "object1Type": object1type,
                "object1ObjectDesignator": object1object_designator,
                "object1InternationalDesignator": object1international_designator,
                "object1OperatorOrganization": object1operator_organization,
                "object1EphemerisName": object1ephemeris_name,
                "object2Type": object2type,
                "object2ObjectDesignator": object2object_designator,
                "object2InternationalDesignator": object2international_designator,
                "object2OperatorOrganization": object2operator_organization,
                "object2EphemerisName": object2ephemeris_name,
                "headersOnly": headers_only,
                "size": size,
                "page": page,
                "format": format,
            },
            request_options=request_options,
        ) as _response:

            async def _stream() -> AsyncHttpResponse[
                typing.AsyncIterator[StreamCdmResponse]
            ]:
                try:
                    if 200 <= _response.status_code < 300:

                        async def _iter():
                            async for _text in _response.aiter_lines():
                                try:
                                    if len(_text) == 0:
                                        continue
                                    yield typing.cast(
                                        StreamCdmResponse,
                                        construct_type(
                                            type_=StreamCdmResponse,  # type: ignore
                                            object_=json.loads(_text),
                                        ),
                                    )
                                except Exception:
                                    pass
                            return

                        return AsyncHttpResponse(response=_response, data=_iter())
                    await _response.aread()
                    if _response.status_code == 400:
                        raise BadRequestError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Any,
                                construct_type(
                                    type_=typing.Any,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 401:
                        raise UnauthorizedError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Any,
                                construct_type(
                                    type_=typing.Any,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 403:
                        raise ForbiddenError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Any,
                                construct_type(
                                    type_=typing.Any,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 404:
                        raise NotFoundError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Any,
                                construct_type(
                                    type_=typing.Any,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 405:
                        raise MethodNotAllowedError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Any,
                                construct_type(
                                    type_=typing.Any,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 417:
                        raise ExpectationFailedError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Any,
                                construct_type(
                                    type_=typing.Any,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 429:
                        raise TooManyRequestsError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Any,
                                construct_type(
                                    type_=typing.Any,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 500:
                        raise InternalServerError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Any,
                                construct_type(
                                    type_=typing.Any,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 502:
                        raise BadGatewayError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                ErrorResponse,
                                construct_type(
                                    type_=ErrorResponse,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 503:
                        raise ServiceUnavailableError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                ErrorResponse,
                                construct_type(
                                    type_=ErrorResponse,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    _response_json = _response.json()
                except JSONDecodeError:
                    raise ApiError(
                        status_code=_response.status_code,
                        headers=dict(_response.headers),
                        body=_response.text,
                    )
                except ValidationError as e:
                    raise ParsingError(
                        status_code=_response.status_code,
                        headers=dict(_response.headers),
                        body=_response.json(),
                        cause=e,
                    )
                raise ApiError(
                    status_code=_response.status_code,
                    headers=dict(_response.headers),
                    body=_response_json,
                )

            yield await _stream()
