# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from .raw_client import AsyncRawSchemasClient, RawSchemasClient


class SchemasClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSchemasClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSchemasClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSchemasClient
        """
        return self._raw_client

    def get_xsd(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[str]:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[str]
            OK

        Examples
        --------
        from tracss import TraCSS

        client = TraCSS(
            client_id="YOUR_CLIENT_ID", client_secret="YOUR_CLIENT_SECRET",
        )
        client.metadata.schemas.get_xsd()
        """
        _response = self._raw_client.get_xsd(request_options=request_options)
        return _response.data

    def get_json(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[str]:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[str]
            OK

        Examples
        --------
        from tracss import TraCSS

        client = TraCSS(
            client_id="YOUR_CLIENT_ID", client_secret="YOUR_CLIENT_SECRET",
        )
        client.metadata.schemas.get_json()
        """
        _response = self._raw_client.get_json(request_options=request_options)
        return _response.data


class AsyncSchemasClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSchemasClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSchemasClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSchemasClient
        """
        return self._raw_client

    async def get_xsd(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[str]:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[str]
            OK

        Examples
        --------
        import asyncio

        from tracss import AsyncTraCSS

        client = AsyncTraCSS(
            client_id="YOUR_CLIENT_ID", client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.metadata.schemas.get_xsd()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_xsd(request_options=request_options)
        return _response.data

    async def get_json(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[str]:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[str]
            OK

        Examples
        --------
        import asyncio

        from tracss import AsyncTraCSS

        client = AsyncTraCSS(
            client_id="YOUR_CLIENT_ID", client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.metadata.schemas.get_json()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_json(request_options=request_options)
        return _response.data
